### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#103]
Babel  5 -> 6

**Comment by kaizvn** [comment]
I made my fork run on babel 6 already. I hope it helps people who want to run this awesome project in latest babel.

For someone get error with .babelrc `extra` option, I found a way to fix it: 
```
{
  "presets": [
    "es2015",
    "react"
  ],
  "env": {
    "development": {
      plugins: [
        ['react-transform', {
          transforms: [
            {
              transform: 'react-transform-hmr',
              imports: ['react'],
              locals: ['module'],
            }, {
              transform: 'react-transform-catch-errors',
              imports: ['react', 'redbox-react'],
            },
          ],
        }],
      ]
    }
  }
}
```

**Comment by choonkending** [comment]
@kaizvn Of course man! Definitely willing to see your PR. Thanks for contributing. :) Babel 6 has been sitting in my backlog for a while now, so it would be great if you could help out :)

**Comment by kaizvn** [comment]
@choonkending I've made a pull request already, please have a look on it  :smile:

**Comment by kaizvn** [comment]
@choonkending after read some articles, I found out that ES7 doesn't support `decorator` yet, so that if people's going to use any `@decoratorName` in this project, it will throw  `Unexpected token` error. 
So, my PR just fit for any projects that doesn't use `decorator`, so sad.

**Comment by choonkending** [comment]
@kaizvn I'm having a look at your PR right now. 

> could you please explain me about the presets stage-0,1,2,3 etc... ?

Babel transforms the features we want from ES6 or ES7 into ES5 (what is supported by most modern browsers). If you try using it [here](https://babeljs.io/repl/), you'll see that your ES6 syntax gets transformed into syntax the browser understands.

Presets to my understanding are a collection of the plugins we want to use. For example, for ES2015/ES6, we use preset 2015. That will include arrow functions, classes, etc. Read more [here](http://babeljs.io/docs/plugins/preset-es2015/).

As for stage-0, stage-1, etc, those are proposed changes for ES7 (ecma262). Link to repository [here](https://github.com/tc39/ecma262). These include decorators (stage-1), async generators (stage-3). Some of these might change or removed, so use with caution. 

To know what babel preset you should use, check [this](http://babeljs.io/docs/plugins/). Hope that helps.

**Comment by choonkending** [comment]
@kaizvn Any luck you could take a look at your PR and get it ready for merging? Babel 6 is pretty standard now, and it would be worth looking into transitioning from Babel 5 to 6 with your help :smile: 

Let me know if you have the capacity to deal with the PR currently, otherwise I'm happy to create a branch + PR for this.

**Comment by alexhawkins** [comment]
+1 on Babel 6 PR

**Comment by choonkending** [comment]
:ship:

**Comment by kaizvn** [comment]
sorry dude I was busy with my own project :(! I hope I could help you later, terrible sorry!

**Comment by choonkending** [comment]
All good man. Your initial PR was a good reference for me to start with :)
