### ISSUE TITLE
css is not loading id devHotLoader mode

### ISSUE THREAD

**Issue by bokzor** [choonkending/react-webpack-node#109]
Hi, It seems that the css is not loaded in 'devHot'. I've just made few change but I have no idea how to debug this....

**Comment by choonkending** [comment]
@bokzor Thanks for raising this issue.

Which branch are you in now? Can you pull the latest master? Devhot is no longer being used ;)

**Comment by bokzor** [comment]
The branch flux/alt

**Comment by choonkending** [comment]
@bokzor I might have to look at that later. `devHotLoader` wasn't working as expected :( I will see if there is fix for this.

**Comment by choonkending** [comment]
@bokzor In the meantime, if you find a fix for this, let me know :) Currently focusing efforts on making the master branch with redux better.
