### ISSUE TITLE
README in different languages?

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#110]
Would be interesting to write it in 简体中文 or other languages.

Not sure if valuable to non-native English speakers. Just a thought.

**Comment by 1001b** [comment]
Great work in documenting the code and README...it's probably the best in dozen other react-* starter/boiler plate repos...I'm a bilingual...if a visitor manages to find this repo, I don't think he/she will have trouble understanding the commenting or docs...maybe only translating the README is good enough...
