### ISSUE TITLE
react-router 2.0

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#114]
https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md

**Comment by kaizvn** [comment]
@choonkending  just note about `history`, before it was included in NodeJS platform but now it separated already. So remember `npm install --save history` to avoid `undefined error` ( I've experienced with this :joy: ).

**Comment by choonkending** [comment]
@kaizvn Thanks a lot! Will do :)

**Comment by choonkending** [comment]
https://github.com/rackt/react-router/releases still using as release candidates. Will upgrade once it's out of rc (which I expect will be quite soon) :)
