### ISSUE TITLE
devServer

### ISSUE THREAD

**Issue by geraldyeo** [choonkending/react-webpack-node#116]
Not an issue, but I would like to find out in this [code block from server/config/express](https://github.com/choonkending/react-webpack-node/blob/master/server/config/express.js#L91-L105), how does `node_env` get set to `devhotloader` (I don't see it in npm scripts, or anywhere) and where does the file `dev-server` (`require('../dev-server')`) come from?

**Comment by choonkending** [comment]
@geraldyeo Good question! Thanks for asking. 

I believe this was a chunk of code that was not removed after I moved to redux on the master branch.

I'll have a look later to verify this and remove it if necessary. :) :)

**Comment by geraldyeo** [comment]
I see. I was using your repo as reference for creating my own boilerplate. :) But I was getting some issues understanding a few things.

So this [line in server/config/routes](https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L10) relies on the web proxy (`http-proxy`)? I know it references `app/server.jsx`, but I'm not sure if it gets it from webpack's public path or the proxy server.

**Comment by choonkending** [comment]
@geraldyeo 

> So this line in server/config/routes relies on the web proxy (http-proxy)?

I don't believe so. It currently only requires the webpack-compiled file in the public path on the server (not an ideal solution, I am looking into other ways of doing this). Good reminder to remove `http-proxy` as well. Sorry for the confusion. I'll make a PR to remove this.

**Comment by geraldyeo** [comment]
@choonkending Ok cool, thanks for clearing that up.

**Comment by choonkending** [comment]
Removed in https://github.com/choonkending/react-webpack-node/commit/5ff6ab01d542c874f9977ae8c038f3483ee6c7c7

**Comment by geraldyeo** [comment]
@choonkending 

Sorry, had to ask... since node is throwing error, because it cannot find module "../../public/assets/app.server"

If you can point me to where I can find out more, that'll be nice. 
[repo](https://github.com/geraldyeo/universal-react-frontend-boilerplate)
