### ISSUE TITLE
Login does not save user to session

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#117]
On refresh, it does not deserialize the user. Which is killing me. 

Presumably, one of the many dependencies has had a version bump, and broke the world.

**Comment by choonkending** [comment]
Oh god. 
https://github.com/jaredhanson/passport/issues/222

**Comment by shawnxusy** [comment]
I also bumped into this.. tried to follow the resolutions but not working still.. any ideas?

**Comment by choonkending** [comment]
@shawnxusy The fix just pushed fixed it makes it work on http connections, but I'm still looking for a fix for trusting proxies over a HTTPS connection. Something related to config settings. :D

**Comment by choonkending** [comment]
https://github.com/choonkending/react-webpack-node/commit/dfdc8c514f7906c3bfff45ebc55609b417b560c3

**Comment by choonkending** [comment]
Closing as fixed :D. @shawnxusy Feel free to ask any questions if u still encounter this issue.

**Comment by shawnxusy** [comment]
Thanks @choonkending, works great :D
