### ISSUE TITLE
bug in demo

### ISSUE THREAD

**Issue by nodegin** [choonkending/react-webpack-node#120]
before logged in, click to dashboard will produce

`Uncaught Invariant Violation: Stateless function components cannot have refs.`

this crash the login function

**Comment by choonkending** [comment]
Thanks for that. I actually have a fix for that in my local branch. Update
react redux. Will push it up when I have the chance!

**Comment by nodegin** [comment]
That's good

**Comment by choonkending** [comment]
@nodegin Should be fixed. Please reopen if still an issue :)
