### ISSUE TITLE
Invalid checksum after changing components

### ISSUE THREAD

**Issue by nodegin** [choonkending/react-webpack-node#122]
To reproduce the issue:

1. Run the project

2. Edit EntryBox.jsx

3. change `placeholder="What's yer fav idea?"` to `placeholder="What's ur idea?"`

4. Wait for hot reload, after component updated refresh the page

Seems the `public/assets/app.server.js` not updating

**Comment by choonkending** [comment]
@nodegin The idea is of hot reloading is so you won't reload the page. I do not think this is an issue. If you wanted to see how it works like in production (without hot-reloading), `npm run build` and `npm start`, and then refresh, you should not see that error message then.

Closing this issue, but feel free to keep this discussion running.
