### ISSUE TITLE
Vendor files processing for webpack

### ISSUE THREAD

**Issue by shawnxusy** [choonkending/react-webpack-node#123]
I'm quite new to webpack building process, let's say under /app we have a /app/vendor directory with a bunch of .js and .scss.

What would be an ideal additional steps to run in webpack configs? (Looks like it's rather complex even to add Bootstrap to project).

Thanks :)

**Comment by psimyn** [comment]
depends on how you want to reference them from other places.

since 'app' is included in resolve.modulesDirectories in [webpack.config](https://github.com/choonkending/react-webpack-node/blob/master/webpack/webpack.config.dev.js#L70) you can require vendor modules like this:

```
import 'bootstrap' from 'vendor/bootstrap/bootstrap.js';
```

For shorter includes, you can use Webpack's [Resolve Alias](https://webpack.github.io/docs/configuration.html#resolve-alias)

If that's unclear, let me know what is in vendor folder and I can give some better examples.

**Comment by shawnxusy** [comment]
@psimyn thanks for answering! 

The universal rendering is quite new to me - for instance I need to include amcharts library, with amcharts.js, a few stylesheets, and icons. Following your advice, should I import /server/vendor/amcharts/amcharts.js in index.js? Then how about the stylesheets and icons in /server/vendor/amcharts?

Thanks a lot!

**Comment by psimyn** [comment]
Stylesheets and icons you can import like node modules:

```
const icon = require('vendor/icons/smileyface.png');
const styles = require('vendor/something/styles.css');
...
<img src={icon} />
```

However, [amcharts.js](https://github.com/amcharts/amcharts3/blob/master/amcharts/amcharts.js) puts Armcharts object on window (so it wouldn't work for universal rendering). But assuming it is included you should be able to access amcharts things from your react components on client-side.

You can either require it in Components/Pages that you need charts, or put it in App.js to include it everywhere. 

@choonkending any other ideas?

**Comment by choonkending** [comment]
@psimyn I think your idea is pretty solid. I would require it in App.js and use the Amcharts window object from there.

Alternatively, one other method I could think of is to create a Component, e.g. `AmchartWrapper` that:
1. Requires the amchart library
2. Requires all the icons
3. Requires the stylesheets

And then require `AmchartWrapper` whenever you need it.

**Comment by shawnxusy** [comment]
@choonkending @psimyn  Thanks a lot, I am experimenting with AmchartWrapper approach, thinking it will work fine. Great work and appreciate your time guys!
