### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tinhanchanachai** [choonkending/react-webpack-node#128]
When I try to 'npm install'

will show error all time
ERROR in ./client.jsx
    Module build failed: RangeError: Maximum call stack size exceeded

**Comment by choonkending** [comment]
@tinhanchanachai Sorry for the late reply. I'm going to remove `node_modules` and rerun `npm install` now to reproduce this.

**Comment by tinhanchanachai** [comment]
@choonkending  Thank you so much. But after I rerun 'npm install' Will find new error : 
  modulesTypeError: Cannot read property 'visitClass' of undefined

For fixed this error change "babel-eslint" to version "^4.1.7" the last version did't work.

Thank.

**Comment by choonkending** [comment]
@tinhanchanachai Thanks for that. Good work finding the root cause. Do you wish to create a pull request for this fix?

**Comment by choonkending** [comment]
Will push a fix for this soon. Thanks for reporting this @tinhanchanachai !!

**Comment by tinhanchanachai** [comment]
Already to create pull request.
