### ISSUE TITLE
Renamed: Handle Login Flow Properly

### ISSUE THREAD

**Issue by chrislewispac** [choonkending/react-webpack-node#129]
I deployed to heroku, then to my local machine, and am receiving the following error upon attempted login. 

`_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/chrislewis/Projects/aimpointv2/app/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/chrislewis/Projects/aimpointv2/app/node_modules/express/lib/response.js:163:12)
    at /Users/chrislewis/Projects/aimpointv2/app/server/controllers/users.js:19:21
    at allFailed (/Users/chrislewis/Projects/aimpointv2/app/node_modules/passport/lib/middleware/authenticate.js:87:18)
    at attempt (/Users/chrislewis/Projects/aimpointv2/app/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/Users/chrislewis/Projects/aimpointv2/app/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at verified (/Users/chrislewis/Projects/aimpointv2/app/node_modules/passport-local/lib/strategy.js:82:30)
    at Query.<anonymous> (/Users/chrislewis/Projects/aimpointv2/app/server/config/passport/local.js:18:22)
    at /Users/chrislewis/Projects/aimpointv2/app/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /Users/chrislewis/Projects/aimpointv2/app/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
`

**Comment by choonkending** [comment]
@chrislewispac Sorry for the late reply. The reason you're getting this is because this boilerplate does not handle invalid logins (i.e. logins that are not saved into mongoDB).

Can you try pasting this into your console and let me know if this works?

```
var http = new XMLHttpRequest();
var url = "http://localhost:3000/signup";
var params = "email=example@ninja.com&password=ninja";
http.open("POST", url, true);http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");

http.send(params);
```

Good issue though, we need to handle all the possible login states, and not just error out. It's pretty confusing for new users i imagine.

**Comment by chrislewispac** [comment]
@choonkending Yes, that creates a new user in the DB and resolves the error.

**Comment by choonkending** [comment]
@chrislewispac It's good that you raised this issue. I think a proper boilerplate needs to have a proper login/register flow which handles all cases. I'll rename the title.

**Comment by charlieclark** [comment]
I also was confused for a few minutes, before checking here. Would be great to get this into the flow / docs :+1:

**Comment by choonkending** [comment]
@charlieclark Agreed. I will look into getting this done this week if possible. I know it's been tripping people up, and would be not a pleasant experience for people looking to get into react and all.

**Comment by choonkending** [comment]
Just spec-ing it out some of the requirements. It would be good to write some tests for this to increase the unit test coverage in this repo as well. Feel free to comment on the below if you have any thoughts

## Scenarios
### Login
- [ ] Given `a@email` does not exist in database, 
When I login with `a@email.com`, 
Then I will be notified with a message "Your email or password combination is not correct" (or similar)
- [ ] Given `a@email` exists in the database, 
When I login with `a@email.com` with correct credentials, 
Then I will be redirected to the home page with a message "You have been successfully logged in"
- [ ] Given `a@email` exists in the database, 
When I login with `a@email.com` with *incorrect* credentials, 
Then I will be notified with a message "Your email or password combination is not correct" (or similar)

### Registration
- [ ] Given `a@email` does not exist in database, 
When I register with `a@email.com`, 
Then I will be notified with a message "You have been successfully registered"
- [ ] Given `a@email` exists in the database, 
When I register with `a@email.com`, 
Then I will be notified with a message "Email already exists"

### No Auth Access
TBD

## Out of scope
- Email checking

**Comment by charlieclark** [comment]
To avoid confusion, I think that:

"Given a@email does not exist in database, When I login with a@email.com"

Should be notified with a message "There is no record of this email" (or similar)

**Comment by choonkending** [comment]
@charlieclark Good point! I was thinking from a security perspective people can then test to see if someone's email is in the database. Butttt....I agree that avoiding confusion in this instance is the better way to go :hamburger:

**Comment by choonkending** [comment]
In scope:
- [ ] Ensuring the API endpoints for login, logout and register are correct + RESTful.
- [ ] Replacing `isomorphic-fetch` with axios

**Comment by choonkending** [comment]
This might also be a suitable time to consider making the API is more restful.

@charlieclark What do you think of a solution such as this? http://stackoverflow.com/a/7252311/1710968
Would be great to get more opinions on the API before I begin fixing the login/register flow properly.

**Comment by choonkending** [comment]
Closing for now. Can re-open when we find more cases to fix for the login flow.
