### ISSUE TITLE
Abstract `fetchTopics` 

### ISSUE THREAD

**Issue by charlieclark** [choonkending/react-webpack-node#134]
Right now the example's server side async rendering is specific to getting the `topics`. It could be helpful to abstract this a little bit to accommodate for a more configurable way to define async calls that are page specific. I might have a stab at this - let me know if you'd be interested in a PR, or if you're keeping it intentionally simple.

**Comment by choonkending** [comment]
Go for it! I did that as an MVP, but happy to make it more usable for
everyone. Thanks mate!

**Comment by choonkending** [comment]
@charlieclark How are you going with this one?

I'm really interested in how you're doing this. One approach I've seen is, you define a static method across all route handlers that you then call to make a `async` call. It would be interesting to have a bit of visibility or keep the discussion going.

**Comment by charlieclark** [comment]
@choonkending 

I haven't had much time to implement, but I've been doing research on how to do this in the best way possible.

This seems to be the most common implementation, which integrates nicely with the exiting redux flow:

- a static reference is defined on containers/components that need to fetch async data before a server-side render ( either a function returning an action or an array of actions )
-  a method like `fetchComponentDataBeforeRender` is called after route matching, which loops through the matched components and collects an array of promises which it dispatches.
- Each action dispatches a Promise, which needs to be handled by a promise middleware.
- Once all the promises are resolved, the state now contains all the data we need, and we're ready to render.

I especially like the implementation in this example because it's quite simple:
https://github.com/caljrimmer/isomorphic-redux-app

Let me know what you think!

**Comment by choonkending** [comment]
@charlieclark Thanks! :v: Yes to all of the suggestions! Been doing some research myself.

> a static reference is defined on containers/components that need to fetch async data before a server-side render ( either a function returning an action or an array of actions )

I've seen this in production and it works pretty well. It's good that we're iterating on the current solution as I am not a fan of having just `fetchTopics`.
