### ISSUE TITLE
Favicon and other images do not load

### ISSUE THREAD

**Issue by zamiang** [choonkending/react-webpack-node#146]
Issue is currently visible on the demo site. If you visit https://react-webpack-node.herokuapp.com/ you will see no favicon. If you view-source and visit one of the favicon / meta images. It will be blank.

If you open the image in a text editor, it is being rendered as a data url with exports. ie: ```module.exports = "data:image/png;base64,AAABAAEAIx8AAAEACAB8CQAAFgAAACgAAAAjAAAAPgAAAAEACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCQkIAYxbLAFIW2wBVFuIAVx3PAEtLSwBDGfkATU1NAEkm7wBqK9gAWFhYAFlZWQBcXFwAYmJiAGZbegBkZGQAZWVlAG5ubgBvb28AcXFxAHFxcgBycnIAc3NzAHR0dAB0fF0AdXV1AHh3eAB4eHgAnl3JAHl5eQB6enoAe3t7AHx8fAB9fX0Afn5+AH9/```.

**Comment by choonkending** [comment]
Thanks for raising this issue. I've noticed this as well, will have a look!

**Comment by choonkending** [comment]
https://github.com/choonkending/react-webpack-node/commit/b187dbb05d271d29332fd999040073344de22ce7 should fix it. 

:) Thanks for that @zamiang. Please re-open if you think it can be improved!

**Comment by tadwhitaker** [comment]
I ran everything start to finish all the way through heroku open without any issues. (Bravo for that, seriously.) When I try opening the deployed version, I get the following favicon issue and am not sure where to go from here:

GET https://guarded-lowlands-41879.herokuapp.com/favicon.ico 503 (Service Unavailable)

I assume it's just not reading app/images/favicon.png.

Looking through b187dbb, changes are:

A) Already made in the helmconfig file
B) I don't have a webpack/webpack.config.dev.js file and instead have webpack.config.dev-client.js and webpack.config.dev-server.js files. Those look like they've been updated further/beyond what's written here and are as follows:

{ test: /.json$/, loader: "json-loader" },
{
test: /.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
loader: 'url',
query: {
name: '[hash].[ext]',
limit: 10000,
}
},
