### ISSUE TITLE
Add page-transition

### ISSUE THREAD

**Issue by MadeInMoon** [choonkending/react-webpack-node#151]
Hi everybody,
I added page transitions with "ReactCSSTransitionGroup" (react-addons-css-transition-group), would it be considered has an ui enhancement, and deserves a pull request, or is it out of topic? I'm new, sorry for asking that.

**Comment by choonkending** [comment]
@MadeInMoon 

I personally am a fan of CSS transitions, so I'm happy to see the code!

> I'm new, sorry for asking that.
Haha, we're all learning here. Happy to have you contributing.

I do worry that it might make the boilerplate a bit bloated (for beginners who do not want css transitions), so it would be nice to have a look at the suggested code here (even a snippet) and we can take it from there. Might be worth adding an extra page for UI stuff perhaps (or even a new repo lol).

**Comment by MadeInMoon** [comment]
Ok Sir I'm preparing a clean snippet, and a demo online!

Your project is magic, and in my sens, adding transitions make it become so smooth, so pure, and almost addictive :) 

I also have the feeling that this isomorphic/react/node/etc. environnement can make you feel so confidente with your code, with data, maintenance, ui/ux, without being closed into a framework or a technology, so thanks again to you, and to everybody permitting to other people to learn deeper and cleaner.



------------------------------------------------


Waiting the full code:

I faced a problem linked to the issue [#147 ](https://github.com/choonkending/react-webpack-node/issues/147) :+1: 

I had to remove the '__[hash:base64:5]', from this two files:
**/webpack/webpack.config.dev.js**
```
    module: {
      loaders: commonLoaders.concat([
        { test: /\.scss$/,
          loader: 'style!css?module&localIdentName=[local]__[hash:base64:5]' +
            '&sourceMap!autoprefixer-loader!sass?sourceMap&outputStyle=expanded' +
            '&includePaths[]=' + encodeURIComponent(path.resolve(__dirname, '..', 'app', 'scss'))
        }
      ])
    },

```

**/webpack/webpack.config.prod.js**
```
var commonLoaders = [
  ... ... ....
  { test: /\.scss$/,
    loader: ExtractTextPlugin.extract('style-loader', 'css-loader?module&localIdentName= [local]__[hash:base64:5]!autoprefixer-loader!sass?includePaths[]=' + encodeURIComponent(path.resolve(__dirname, '..', 'app', 'scss')))
  }
];
```



.. in order that the css selectors can match dom elements:
**main.scss**
```
.page-enter {
  opacity: 0.01;
}

.page-enter.page-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}

.page-leave {
  opacity: 1;
}

.page-leave.page-leave-active {
  opacity: 0.01;
  transition: opacity 300ms ease-in;
}
```


So I might need a little help or few advices to respect the isomorphic markups, and the postCSS philosophy, once I'll provide the code ;)

**Comment by choonkending** [comment]
@MadeInMoon Good work! Glad that this repository helped you with learning :smile: 

The code looks good and understandable. I haven't used `React.cloneElement` before, so would have to read up on that. 

> So I might need a little help or few advices to respect the isomorphic markups, and the autoprefixer philosophy, once I'll provide the code ;)

Happy to look at the code when you're ready. :+1:

**Comment by MadeInMoon** [comment]
I forked [here](https://github.com/MadeInMoon/react-webpack-node)! I resumed what I added in the readme.

( I added background color in About.jsx and Dashboard.jsx for you we can see the nice effect of transitions.)

(I didn't imporved the standard opacity transition given in the official react [example](https://facebook.github.io/react/docs/animation.html), so it could even be better)

-----------

 - 1 little issue : In the broswer console (because of the removed  '__[hash:base64:5]'):

> (client) 042ex30u8.2.$=1$0=0106509904004633427"><
> (server) 042ex30u8.2.$=1$0=016004176996648312"><h

-----------

Maybe that it could be a good idea to integrate that in  #156 , or it could be a bad idea if people need and want to focus on the isomorphic/react/mongo/express/etc. tech.

Or as you mentioned before, create an other repo, but wouldn't be a too small changement to justify it?

**Comment by choonkending** [comment]
Thanks mate. I'll take a look at the hashing problem when I get the chance.
Good work!

I agree, might not be worth creating a separate repo, but it might
confusing for new comers using react router to have the ontransitionenter
in App.jsx.

Maybe we could try it on one page if possible and add that to the readme
for animations - maybe wrap About with the transition group. I might be
wrong - viewing the code through my phone currently.

Hehe! Thanks for the hard work and feedback!

**Comment by MadeInMoon** [comment]
You're welcome, it's a pleasure to contribute!

---------
The hashing problem sould disappear if you switch to postCss no?

--------

What would you like to animate in the About.jsx? Simple texts?

And do you think about this architecture? :

App/About/ReactCSSTransitionGroup/{content}

**Comment by choonkending** [comment]
@MadeInMoon Sorry I did not notice this!

> The hashing problem sould disappear if you switch to postCss no?
I just removed the basic hashing for the postcss (just merged in), so let me know how that works for you.

> What would you like to animate in the About.jsx? Simple texts?
Sounds good to me! I generally love animations :) 

> App/About/ReactCSSTransitionGroup/{content}
Do you mean

```javascript
About.jsx
<ReactCSSTransitionGroup>
   {content}
</ReactCSSTransitionGroup>
```

Yeah, I'm not fussed about that. I would like to add that to the docs, to say Animated Page Transition or similar :)

**Comment by MadeInMoon** [comment]
@choonkending no pb!!

I'll try again as soon as I can (few days maximum), to re-implement it within the last repo.

> Maybe we could try it on one page if possible and add that to the readme
for animations - maybe wrap About with the transition group

When i saw your sentence above,I said to me that you wanted to do like that : 

    About.jsx
    <ReactCSSTransitionGroup>
       {content}
    </ReactCSSTransitionGroup>`

But maybe it's not the usage you wanted to? And maybe you only want to add that to the doc and not in the code? I'm not a native english speaker so don't hesitate to be clear and directive with me ;)

**Comment by choonkending** [comment]
We could use a higher order component to add a CSSTransitionGroup so our existing components won't get affected as much and it would be relatively to remove if you like. https://github.com/choonkending/useful-js-patterns/blob/master/higher-order-components/hOC.js
