### ISSUE TITLE
Slim & stateless version of the boilerplate

### ISSUE THREAD

**Issue by dzotokan** [choonkending/react-webpack-node#156]
Cloned the project and didn't need any of the auth/db/models things.

Any thoughts on stripping those out and maybe creating a separate branch?

i.e. Static react app with routes and an empty `need` maybe, with no authentication and DB. Would be more suitable in a microservices architecture land perhaps.

Happy to write up a PR removing those things (not for `master` obviously).

**Comment by choonkending** [comment]
@dzotokan Definitely! 

This has been bothering me because it took me at least 30 minutes stripping it out that day. 

>  Static react app with routes and an empty need maybe, with no authentication and DB. Would be more suitable in a microservices architecture land perhaps.

Good thinking. Perhaps we only need to keep that branch up to date when there are webpack or config changes then.

**Comment by choonkending** [comment]
I'm going to try to work on this guy. The refactoring here will mainly be in the `server/` folder.

The easiest approach I can think of is to:
- abstract connecting + authentication + model creation  into a different file - so people can easily comment that out if you wish to switch databases/not use a database.

I'll have a go to see how much work this will take + whether it's a good solution

**Comment by choonkending** [comment]
Closing as issue is tacked in #372
