### ISSUE TITLE
how to use ES6 in production env

### ISSUE THREAD

**Issue by HellMagic** [choonkending/react-webpack-node#164]
i have realized the recently commit about babel6, and i have successfully used ES6 through babel doc, but when i exec "npm run build" and "npm run start" followed the doc there is error throw where ES6 code exist. so, how can i use ES6/7 in this awesome react-webpack-node?if there is anything i have missed?

**Comment by choonkending** [comment]
@HellMagic Thanks for raising this issue.

Can you provide a bit more context as to what error message you see? You should be able to write ES6 code for client side.

**Comment by HellMagic** [comment]
@choonkending Thanks for your reply. First, i should apology, because i didn't say clearly the error just be throwed when i write es6 code in server side, like routes file. 
the error message not so helpful, just said "let is not defined,...", because i used "let" syntax. And, i have fixed it just now, i through configed a script in package.json file, like "build:server": "babel --presets es2015,stage-0 server -d build"(of course, you should modify the start node file, like "node build/index.js"), then it work. i didn't know if this way is good practice in the project boilerplate, maybe there is better way.
oh, btw, very glad to see merged the code about nodemon, this is very helpful, and i just want to fix it, cool work!!!
en, now, i suggest if  we can add css loader, font load, image loader, and the optimization for them, especially use in production env, the most import, long-term-cache config.
that's just my suggestion, hope some helpful and looking forward to your reply~ cheers~~~

**Comment by choonkending** [comment]
@HellMagic Thanks for that!

Hopefully the latest commit actually solves the initial server error you had.

> i suggest if we can add css loader, font load, image loader, and the optimization for them, especially use in production env, the most import, long-term-cache config

Definitely! We already use css-loader, but I'm in the process of adding postcss plugins into the build and removing sass from the stack - https://github.com/choonkending/react-webpack-node/issues/150 . It would definitely be good to load fonts + long-term-cache config :+1: 

I'll look into that after I finish the postcss branch and [socket example](https://github.com/choonkending/react-webpack-node/issues/163)

**Comment by HellMagic** [comment]
@choonkending  very coooooool~~~
postcss maybe the best practice~it make the task more clear!
the project is awesome, hope it better and better, :beers:

**Comment by choonkending** [comment]
@HellMagic Thanks man! :beers: 

If you don't any objections, I will close this issue. Please feel free to contribute/raise any issues if you find any. :smile:
