### ISSUE TITLE
Better use of alt and utils

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#17]
There are tons of goodies to be used from the alt [utils](https://github.com/goatslacker/alt/tree/master/src/utils). I'd like to provide a really solid starting point with good examples of how to utilise them.

**Comment by choonkending** [comment]
Also update to https://github.com/goatslacker/alt/blob/master/CHANGELOG.md#0171

**Comment by choonkending** [comment]
Might consider using this https://github.com/goatslacker/alt/blob/master/src/utils/AltIso.js

**Comment by joshhornby** [comment]
Might be worth using https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js or https://github.com/goatslacker/alt/blob/master/components/AltContainer.js if you are considering an alt refactor.

**Comment by choonkending** [comment]
As a matter of fact I am, and have been considering these good utils, but
haven't tested them out yet :)

Thanks! @joshhornby

On Thu, Jul 23, 2015 at 11:12 PM, Josh Hornby <notifications@github.com>
wrote:

> Might be worth using
> https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js
> or
> https://github.com/goatslacker/alt/blob/master/components/AltContainer.js
> if you are considering an alt refactor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choonkending/react-webpack-node/issues/17#issuecomment-124092965>
> .
>



-- 
Kind regards,
Choon Ken Ding

**Comment by choonkending** [comment]
Maybe it's also worth waiting for https://github.com/goatslacker/alt/pull/364 that could potentially replace our `UniversalRenderer`.js

**Comment by choonkending** [comment]
https://github.com/choonkending/react-webpack-node/pull/61
