### ISSUE TITLE
app shows "React Webpack Node" above the nav

### ISSUE THREAD

**Issue by philohelp** [choonkending/react-webpack-node#175]
Everything seemed correct (I installed some modules like react-toolbox which appears buggy, inline-grid, draftJS, radium and some minor ones) then I restarted the server : now the app is loaded & rendered correctly but it doesn't load any data and it shows "React Webpack Node" on top of the navbar. No error message whatsoever. As nothing tells me where the problem is coming from, do I get a chance to know what's going on without having to remove the app pieces after pieces ? Thanks a lot for your help.

**Comment by philohelp** [comment]
Fun is back. Lightspeed with all features, it rocks. Problem may have been caused by :
- Image server cant find
- Real trouble with webpack loading fonts - I dont know where to put them at first...
- Bug in react-toolbox list components. Ill figure out.
But by the time Id really love to know what happens when app shows "React Webpack Node" above the nav.

**Comment by caranicas** [comment]
I've had that happen to me as well. It seems to happen when there is an issue with the hand off from what the server rendered to what the client has expected the server to render. If you try cleaning and rebuilding and you still see it, then I would just work backwards until you figure out which is the problem module.

**Comment by psimyn** [comment]
gonna close this one. Please re-open if you have it happen again philohelp and I can try to reproduce. Thanks!
