### ISSUE TITLE
How do dev-server, dev-client and express fit together?

### ISSUE THREAD

**Issue by sebkouba** [choonkending/react-webpack-node#182]
I can't figure out how the pieces fit together. I'm trying to understand the scenario where the project is run in dev mode. From what I understand:

1. build:dev is run executing webpack.config.dev-server.js
This produces a server.js file in /public/assets. Is that file ever used? One comment suggests this is where we prepare the server side rendering. Is that the case? What are the outputs from this operation and how are they used?

2. server/index.js is executed
This starts our express server and when we are in dev mode it hooks up the hot reloading. I found [this explanation](http://madole.xyz/setting-up-webpack-dev-middleware-in-express/) for how that works. It seems like that's what we are doing, which makes sense.

It seems possible to just run `node server/index.js` and everything works. That's why I don't understand how the dev-server.js fits into the equation.

I would appreciate any hints or resources regarding this topic. Thanks!

**Comment by psimyn** [comment]
server.js is used as `compiled_app_module_path` in [routes](https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L11)

`server/index.js` is used to run everything, it has some extra stuff in dev mode.

For finding the starting points (or what gets run), you can start in [`package.json`](https://github.com/choonkending/react-webpack-node/blob/master/package.json). The `start` task runs [`server/index.js`](https://github.com/choonkending/react-webpack-node/blob/master/server/index.js) directly, while `npm run dev` references [`nodemon.json`](https://github.com/choonkending/react-webpack-node/blob/master/nodemon.json) (which runs `server/index.js`)

Hope that helps explain a bit
