### ISSUE TITLE
Problem with the latest nock version.

### ISSUE THREAD

**Issue by hillscottc** [choonkending/react-webpack-node#186]
In the package.json file, you have floating version of 
"nock": "^7.2.2"
As of now, that fails trying to grab the latest version 7.7.1, which appears broken in npm somehow.
So I changed the dependency SPECIFY the earlier 7.22 version. (No ^)
  "nock": "7.2.2",

**Comment by choonkending** [comment]
There's a latest of nock which appears to be working fine. So i'll bump it up to 8.0
