### ISSUE TITLE
eslint unexpected token = 

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#19]
Moving to [ES6](https://github.com/choonkending/react-webpack-node/blob/master/docs/ReactInES6.md) made things a bit weird for eslint.
![screen shot 2015-06-08 at 12 54 06 am](https://cloud.githubusercontent.com/assets/3787885/8024523/264125f0-0d7a-11e5-8a60-46c3bef9fb8e.png)

Tried debugging it but no luck.

Any ideas @psimyn?

**Comment by psimyn** [comment]
needs to use to babel-parser

https://github.com/psimyn/react-webpack-node/commit/a40611f8be1101db622443e0c0fdd03aec8323f8

**Comment by choonkending** [comment]
Thanks! Too much of a champion! :+1: 

Fixed that issue. Will sort out the sort-comp error when I get the chance!

**Comment by choonkending** [comment]
sort-comp error fixed.
