### ISSUE TITLE
Get redux devtools working

### ISSUE THREAD

**Issue by mjewell** [choonkending/react-webpack-node#191]
Currently ```createDevToolsWindow.js``` exists but isn't being used anywhere. I tried some simple stuff to configure it but ended up with some errors. Not sure if I had something set up wrong or if it's broken but [this](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md) has some instructions on how to set it up and it seemed like some stuff was missing. If I just did something wrong then maybe we should add something to the readme to explain how to set it up.

Additionally/alternatively, it would be nice to support the [chrome extension](https://github.com/zalmoxisus/redux-devtools-extension). That has some benefits like not having to worry about production vs dev, and being simpler to configure

**Comment by choonkending** [comment]
Good pick up. I removed it's usage awhile ago when I refactored, but never got around to removing it. 

I'm not sure how valuable it is in development (given we have something like redux-logger). Sorry I haven't had the time to properly read redux-devtools to see if it's worth keeping. What do you reckon?

I like the idea of the chrome extension.

**Comment by mjewell** [comment]
I'm not really sure how useful it would be, I mostly just thought it looked cool and wasn't sure how to get the existing code working. Seems like nice to be able to do the time traveling and stuff, and the chrome extension is pretty easy to support so might be worth it

**Comment by mjewell** [comment]
Chrome extension support added in #194
