### ISSUE TITLE
Front end routing does not fetch data for component

### ISSUE THREAD

**Issue by AJIh** [choonkending/react-webpack-node#202]
`Vote.need` functions are only called in server side. When clicking `Ninja Ocean` to navigate to index route, the `Vote` component's props are not fetched at front end.

**Comment by AJIh** [comment]
I tried to add a function to `client.jsx`. 

```javascript
...

function onUpdate() {
  const { state: { components, params } } = this;
  fetchComponentDataBeforeRender(store.dispatch, components, params);
}


// Router converts <Route> element hierarchy to a route config:
// Read more https://github.com/rackt/react-router/blob/latest/docs/Glossary.md#routeconfig
render(
  <Provider store={store}>
    <Router history={history} onUpdate={onUpdate}>
      {routes}
    </Router>
  </Provider>, document.getElementById('app'));
```

This will make `window.__INITIAL_STATE__` useless. Because `Router` will trigger `onUpdate` when first loaded in page.

**Comment by AJIh** [comment]
@choonkending . I have created a PR to fix this.

 The repo inspired me a lot. Thanks. :)

**Comment by choonkending** [comment]
@AJIh Thanks for contributing!! I'll have a look when I get the chance! Do you mind rebasing your PR with the latest changes from master? I merged some changes.

So if you have this main repository as your upstream remote,
```bash
// upstream =  git@github.com:choonkending/react-webpack-node.git
git pull -r upstream master
```
in your `/fix-frontend-route-fetch` branch to replay your changes on top of the commit history.

**Comment by choonkending** [comment]
> The repo inspired me a lot. Thanks. :) 

Glad to know it helps! 👍 👍 🚀

**Comment by choonkending** [comment]
Just had a look at this issue. Thanks for the PR.

This issue has been bothering me quite a while.

To summarise for those reading without context:

**Problem**
Client side does not asynchronously *fetch data* on navigation.

**Steps to reproduce**
> When navigating from /login to /, Vote component data is not fetched.

**Reason**
*fetch data* only happens on server-side route matching in `server.jsx`.

**Approach**
1. use `react-router`'s [onUpdate](https://github.com/reactjs/react-router/blob/master/docs/API.md#onupdate) transition hook that is called whenever the router updates its state in response to URL changes.

The excellent example provided in https://github.com/choonkending/react-webpack-node/pull/203

**Pros**:
- It makes sense to trigger the *fetch data* call on the `Router` level, and is easy to understand.

**Cons**:
- Can't think of anything

2. [Note this is just another approach I've seen that works]. Use [match](https://github.com/reactjs/react-router/blob/master/docs/API.md#match-routes-location-history-options--cb) for both client and server side changes, and on `client.jsx` listen to browserHistory changes, and trigger the `match` function every time.

**Pros**
- Might be able to reuse the same `match` function.

**Cons**
- Hard to understand.

**Extra Info**
*fetch data*: `fetchComponentDataBeforeRender` - which calls all the static `need` methods that make API calls.

@AJIh I agree with your approach as it seems cleaner. I'd like to think a little further as to what (unseen) issues might crop up, but will merge this in once I test it (hopefully today or tomorrow).

Thanks a lot buddy!
