### ISSUE TITLE
fetchTopics is called twice

### ISSUE THREAD

**Issue by huyphamily** [choonkending/react-webpack-node#204]
I recently found that fetchTopics was called twice on initial page load.

If you add a console log to your topics/controller/all, you will see it display twice in your console on initial page load.

I believe it has to do with this line of code in fetchComponentDataBeforeRender:
```
const needs = components.reduce((prev, current) => {
    return (current.need || [])
      .concat((current.WrappedComponent ? current.WrappedComponent.need : []) || [])
      .concat(prev);
    }, []);
```

I added a console log after this line to see what needs equal and the result was this:
`[ [Function: fetchTopics], [Function: fetchTopics] ]`

I believe the Higher Order Component created from the connect function will have the need property that will be similar to it's WrappedComponent's need property, creating a duplicate.

**Comment by huyphamily** [comment]
woops, saw an issue was created already.

**Comment by CntChen** [comment]
This issue is related to [#201][#201].

[#201]:https://github.com/choonkending/react-webpack-node/pull/201
