### ISSUE TITLE
Using Bootstrap CSS

### ISSUE THREAD

**Issue by jesshmusic** [choonkending/react-webpack-node#208]
Is there a way to use Bootstrap? I cannot figure out how to get that going with the ExtractTextPlugin.

**Comment by huyphamily** [comment]
I answered a previous issue, hope this helps you as well.
https://github.com/choonkending/react-webpack-node/issues/196

**Comment by choonkending** [comment]
@huyphamily Thanks for answering! 

@jesshmusic Please reopen if you still have issues with this, will be happy to help.

**Comment by hack0001** [comment]
To use a bootstrap CDN in development try this in `pageLink()` in the pages directory.

  ```
  if (module.hot){
      return [
      { rel: 'stylesheet', type: 'text/css', href:'https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css' }
      ];
    }
    return [];
  }
```
