### ISSUE TITLE
should we still not commit sequelize_config.js?

### ISSUE THREAD

**Issue by WestleyArgentum** [choonkending/react-webpack-node#209]
https://github.com/choonkending/react-webpack-node/blob/master/server/db/sequelize/sequelize_config.js

The warning at the top was added back when the file was automatically generated, but it seems pretty generic and nice now. If we don't commit it, and try to build somewhere new, won't that be a pain? Is there any downside to committing it?

**Comment by mjewell** [comment]
Oops, my bad. Yeah, that is fine to check in. The ```sequelize_config.js``` in the ```server/db/postgres``` folder may potentially be worth warning about depending on if you decide to put any sensitive info in there, although right now it just uses obvious and non-sensitive defaults (root username, null password, localhost)
