### ISSUE TITLE
advice for stripping out server side rendering?

### ISSUE THREAD

**Issue by WestleyArgentum** [choonkending/react-webpack-node#211]
Sorry for creating all the issues.

I'm very new to server side rendering, and I'm actually having a lot of trouble with it. More importantly, I'm not really building anything that will benefit from it.

I like the backend api setup in this repo, but I'm thinking about replacing the front end with a static app. This seems tricky though, so I just thought I'd ask to see if you had any advice?

**Comment by choonkending** [comment]
Sure! There should be a couple of things to look out for :

1. Replace the routes.js for any endpoint to serve a static template using
something that will render HTML (jade, etc). (Remember still to set
window.__INITIAL_STATE so the stores will initialise)

2. You no longer need server.jsx, webpack.config for server.jsx, or
anything that references the compiled file in the server/ folder.

I can't think of anything else at the moment (there probably might be some
gotchas).

Do ask any questions, it might be worth documenting the steps you did to
remove SSR for others. :)

**Comment by WestleyArgentum** [comment]
mk, thanks!

**Comment by ArdentKid** [comment]
I'm looking to do this too. Would be nice also to either 1- split up the server code to consume as a standalone crud api, or 2- select which routes will perform SSR (i.e. landing page vs the meat of an interactive app where the user spends most of their time).
