### ISSUE TITLE
Code refactors

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#220]
**Description**
*JS*
- Use stateless functions if possible
- Ensure propTypes used everywhere
- use `mapDispatchToProps` in our connect functions.

**Current implementation**
```javascript
import {connect} from 'react-redux';
class A extends React.Component {
   constructor(props) {
     super(props);
     this.doSomething = this.doSomething.bind(this);
   }
   doSomething() {
          this.props.dispatch(someAction());
   }
   render() {
        return (<SomeComponent onClick={this.doSomething} />
    }
}

export default connect()(A);
```

**Moving forward**
```javascript
class A extends React.Component {
     render() {
        return (<SomeComponent onClick={this.props.onAction} />
     }
}

function mapDispatchToProps(dispatch) {
     return {
         onAction: () => dispatch(someAction)
     };
}

export default connect(null, mapDispatchToProps)(A);
```

*CSS*
- Vertical rhythm to CSS

**Comment by huyphamily** [comment]
What are your thoughts on the short-hand version of mapDispatchToProps, especially when we are not renaming the action creator?

Here's an example:
```
import { createTopic } from 'actions/topics';

class A extends React.Component {
     render() {
        return (<SomeComponent onClick={this.props.createTopic()} />
     }
}

export default connect(null,{ createTopic })(A);
```

**Comment by choonkending** [comment]
Thanks for the suggestion!

Yep I like it, unless we find the need to remap our action type creators. Although it would be less understandable. We can roll with the short-hand version and see how we like it.

```
import { createTopic } from 'actions/topics';

class A extends React.Component {
     render() {
        return (<SomeComponent onClick={this.props.createTopic} />
     }
}

export default connect(null,{ createTopic })(A);
```

I don't think we need to wrap the onClick handler in a function do we? We can just pass in the `prop` as is.

**Comment by huyphamily** [comment]
I agree, you don't need the wrap in this case. As I understand it, and correct me if I'm wrong, if we want to pass in some parameters, then we need to wrap it or use .bind.

`return (<SomeComponent onClick={() => this.props.createTopic('hello')} />`
`return (<SomeComponent onClick={this.props.createTopic.bind(this, 'hello')} />`

**Comment by choonkending** [comment]
@huyphamily You would need to bind it if you're using a function within that component (not the prop) I think. 

Also, using an anonymous function in the `render` method is not a good idea because you would not be able to use Pure Render Mixin or optimise rendering.
