### ISSUE TITLE
Unexpected key "user" found in initialState

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#222]
I'm trying to remove all auth / db related code from the starter kit to have a more clean version, so far so good everything works, there is one bit I am not able to figure out in server.jsx file:

  ```
const history = createMemoryHistory()
  const store = configureStore({
    user: {
      isWaiting: false,
      message: ''
    }
  }, history)

  const routes = createRoutes(store)
```

I'm pretty sure it is this one giving me warning:

`Unexpected key "user" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing". Unexpected keys will be ignored.`

but I believe I do need to create routes with some sort of store, how can I edit this to get rid of the warning?

**Comment by psimyn** [comment]
you can pass an empty object (or maybe `undefined`) to configureStore.

The reason for that error is you removed the `user` reducer from `reducers/index.js`, so it's no longer expecting a `user` as part of the state

[Redux docs for createStore] (http://redux.js.org/docs/api/createStore.html) have some more explanation and examples. Please re-open or comment if you are still having trouble

**Comment by LestaD** [comment]
@psimyn I have same problem. But I want use SSR with redux and webpack chunks (require.ensure).
I need to load reducers dynamic

**Comment by gabrielrtakeda** [comment]
@LestaD Do you solved your problem? I am facing same situation when injecting reducers asynchronously with `require.ensure`.
