### ISSUE TITLE
When npm run dev the app crashes

### ISSUE THREAD

**Issue by horacio-giovine** [choonkending/react-webpack-node#228]
### Description
- Type: Question

Hi all, i just cloned the repo and tried running the app, but the server keeps crashing and i cant figure out why:

i run: npm run dev -> and this is the output:

`> react-webpack-node@1.7.10 dev /Users/horaciogiovine/react-webpack-node
> cross-env NODE_ENV=development nodemon

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/server.jsx app/routes.jsx app/helmconfig.js app/components/Meta.jsx /Users/horaciogiovine/react-webpack-node/server/**/* /Users/horaciogiovine/react-webpack-node/webpack/**/*
[nodemon] starting `npm run build:dev && npm run babel-node -- server/index.js`

> react-webpack-node@1.7.10 build:dev /Users/horaciogiovine/react-webpack-node
> cross-env NODE_ENV=development webpack --colors --config ./webpack/webpack.config.dev-server.js

Hash: 59794b0cb1aeb79568ba
Version: webpack 1.13.0
Time: 86126ms
    Asset     Size  Chunks             Chunk Names
server.js  1.18 MB       0  [emitted]  server
    + 357 hidden modules

> react-webpack-node@1.7.10 babel-node /Users/horaciogiovine/react-webpack-node
> babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"

--------------------------
===> 😊  Starting Server . . .
===>  Environment: development
===>  Listening on port: 3000
===>  Using DB TYPE: MONGO
--------------------------
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/Users/horaciogiovine/react-webpack-node/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (index.js:54:5)
    at Module._compile (module.js:409:26)
    at loader (/Users/horaciogiovine/react-webpack-node/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/horaciogiovine/react-webpack-node/node_modules/babel-cli/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /Users/horaciogiovine/react-webpack-node/node_modules/babel-cli/lib/_babel-node.js:171:48
    at Object.<anonymous> (/Users/horaciogiovine/react-webpack-node/node_modules/babel-cli/lib/_babel-node.js:172:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "babel-node" "--" "server/index.js"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@1.7.10 babel-node: `babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-node@1.7.10 babel-node script 'babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"'.
npm ERR! This is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-webpack-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/horaciogiovine/react-webpack-node/npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...`

This is what i get in the console, the npm-debug.log file has the following:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'babel-node',
1 verbose cli   '--',
1 verbose cli   'server/index.js' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prebabel-node', 'babel-node', 'postbabel-node' ]
5 info prebabel-node react-webpack-node@1.7.10
6 info babel-node react-webpack-node@1.7.10
7 verbose unsafe-perm in lifecycle true
8 info react-webpack-node@1.7.10 Failed to exec babel-node script
9 verbose stack Error: react-webpack-node@1.7.10 babel-node: `babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-webpack-node@1.7.10
11 verbose cwd /Users/horaciogiovine/react-webpack-node
12 error Darwin 14.1.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "babel-node" "--" "server/index.js"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error react-webpack-node@1.7.10 babel-node: `babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"`
17 error Exit status 1
18 error Failed at the react-webpack-node@1.7.10 babel-node script 'babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"'.
18 error This is most likely a problem with the react-webpack-node package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-webpack-node
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-webpack-node
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

Does anyone know why this happens and how can i fix it? btw, i cloned from master.

Thanks in advance

**Comment by brandontle** [comment]
@horacio-giovine did you resolve this? i'm getting the same error.

**Comment by caranicas** [comment]
Do you have other node projects running? `Error: listen EADDRINUSE :::3000` means that the port is already serving something.  I would checkout [http://localhost:3000/](http://localhost:3000/) and see what you have running, and maybe restart your computer.
