### ISSUE TITLE
Problems with watching and recompiling (npm build)

### ISSUE THREAD

**Issue by gsccheng** [choonkending/react-webpack-node#23]
Hi, first thanks for this boilerplate. I'm a beginner.

I ran the npm watch command so I don't need to keep manually rebuilding the app every time there's a change. However, upon running it the app isn't recompiling and I get a huge message, a lot of it that has to do with these type of errors in the react components as shown below

```
WARNING in ./app/components/Vote.react.js
jscs results in errors
  parseError @ line 38 char 13
    Unexpected token =
```

Here is that line 38 it is referring to:

```
 _onChange = () => {
```

It looks like the ES6 isn't being parsed correctly? The app seems to be served properly as I am able to run the app perfectly on localhost. Is it because the babel is only currently meant to render the JS in the front end? Anyone else having these issues? 

I've only done some small tweaks to the boilerplate like setting my own secrets and MongoDB which I don't think causes these errors.

Thanks.

**Comment by psimyn** [comment]
They are just warnings, so shouldn't cause any trouble. jscs was using an experimental parser, that was possibly causing the warnings.

I've added PR to remove it, as style enforcement can be done with eslint. Once that is merged this should fix the warnings.

Thanks for the feedback!
