### ISSUE TITLE
Unable to stop scrolling with overflow hidden on body

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#232]
I'm setting a class to body `.freeze` once my modal is open, this simply makes it `overflow: hidden` this usually prevents window from scrolling, but not in the case with this starter pack, which makes me think there is something to do with scrolling packages here? Could you guys advise on what needs to be tweaked? Did some research, wasn't able to find the issue.

**Comment by psimyn** [comment]
is the class not being applied, or it is and you can still scroll the body?

manually adding overflow: hidden to the body (in devtools) does prevent scrolling. Can you provide your code?

**Comment by IljaDaderko** [comment]
@psimyn The class gets applied correctly, however I am still able to scroll the body.

**Comment by psimyn** [comment]
can you link to code (or the page) so I can take a look?
