### ISSUE TITLE
Optimistic updates

### ISSUE THREAD

**Issue by colinlmcdonald** [choonkending/react-webpack-node#241]
### Description
- Type: Enhancement 
- Related Issue: 140

---------------------------------------------------------------
## Enhancement

**Reason to enhance/problem with existing solution**
Updates should happen on success. If there is no success, error message should happen instead.

**Suggested enhancement**
Move optimistic updates to on success updates in incrementCount, decrementCount, and destroyTopic functions in topics.js. Add .catch to all three as well along with accompanying error messaging.

Also, add testing for those functions as well stubbing out axios and the appropriate method.

-----------------------------------------------------------------

## Question
I can't see a reason for the optimistic updates as opposed to on success updates, but if you have one no problem.

**Comment by choonkending** [comment]
Agreed! Thanks a lot for contributing!!

**Comment by colinlmcdonald** [comment]
No worries! I'll try to have a pull request for you in the next couple of days.

**Comment by colinlmcdonald** [comment]
So I added some error handling for the cases listed above and added an 'error' key to the state. I could work on mapping that to actually displaying the message and adding tests for components as well. 

Let me know if that sounds good and if you had any suggestions/opinion on how the error messaging handling should operate and which component it should go in.

**Comment by choonkending** [comment]
Good work @colinlmcdonald! Thanks a lot for contributing! I'll close this issue, but feel free to re-open if you still have any enhancements/fixes related to this!
