### ISSUE TITLE
a version for react-redux-router server rending

### ISSUE THREAD

**Issue by xiaofan2406** [choonkending/react-webpack-node#242]
## Question
Is it possible to make a branch that's only related to react and server rendering stuff? that is, remove the api server, the mongo stuff.

**Comment by choonkending** [comment]
Yep I think that's a valid concern. Thanks for raising this issue!

Currently what we have is the ability to specify `DB_TYPE.NONE` in [appConfig](https://github.com/choonkending/react-webpack-node/blob/master/server/config/appConfig.js), so we don't execute the mongo/db stuff, but if you have suggestions to improve this `cleaner` version more, feel free to suggest!
