### ISSUE TITLE
Purpose and usage of promiseMiddleware?

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#244]
I'm trying to get a grasp of what `promiseMiddleware` function is used for. Do I just need to dispatch a type of REQUEST and it will than return either a type_SUCCESS or type_FAILURE based on what my api call returns? Or is this used for something else? I'm asking this as in examples provided all 3 types REQUEST, SUCCESS and FAILURE are dispatched manually

**Comment by slavab89** [comment]
In the general thought you are correct. 
If there is no promise in the action - just client side - then it will stop and just call that action.
When you dispatch some action that contains a promise - api call - this middleware will dispatch 2 of the 3 events, REQUEST to indicate that a request has been issued, and SUCCESS or FAILURE to indicate what happened.

In the example that you see for the topics (createTopic), for me it seems like it does several updates and several unneeded dispatches (i might be mistaken here). There is a comment saying that its an optimistic dispatch but the middleware already does that for you
