### ISSUE TITLE
In promiseMiddleware, axios response called "req"?

### ISSUE THREAD

**Issue by benwiley4000** [choonkending/react-webpack-node#246]
## Question

In [`promiseMiddleware`](https://github.com/choonkending/react-webpack-node/blob/master/app/middlewares/promiseMiddleware.js#L17) the `axios` response is referred to as `req`. Is this a typo (should it be called `res`)? I've been using `req` in my own code since I was copying a lot of pieces from this project but I'm starting to think maybe it was a mistake, since the POST request handling (that doesn't use `promiseMiddleware`) uses the word `res`.

**Comment by psimyn** [comment]
good eyes! looks like a typo. If you want to create PR it can be insta-merged, otherwise it'll get fixed up in one of the upcoming cleanups

**Comment by benwiley4000** [comment]
@psimyn: here you go. https://github.com/choonkending/react-webpack-node/pull/264
