### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by nitte93** [choonkending/react-webpack-node#249]
### Description
- Type:  Question

I did `npm install.`
Then `npm run dev.`
It is throwing hte following error.

```
ERROR in ./server.jsx
Module build failed: Error: Couldn't find preset "es2015" relative to directory
``` 
 ```
` throw new Error("Couldn't find preset " + (0, _stringify2.default)(val) + " relative to directory " + (0, _stringify2.default)(dirname));
`
```
---------------------------------------------------------------
## Bug
**Steps to Reproduce**
`npm install`
`npm run dev`

----------------------------------------------------------------

## Question
I then tried to install the preset myself. I did.
` npm install babel-cli babel-preset-es2015
`
This fixed the `es2015 `error, but still it's throwing  an error. This time it is:
`Module build failed: Error: Couldn't find preset "stage-0" relative to directory`
**How to?**
Any suggestion on how to fix this, or did I miss something in the readme file?

**Comment by psimyn** [comment]
did the npm install finish fully?

can try either running it again, or `rm -rf node_modules` and then `npm i` again

if that still breaks, check everything is ok in your package.json

**Comment by choonkending** [comment]
Feel free to reopen if this issue still occurs, closing for now :)

**Comment by kandaraj** [comment]
I had the same issues, and created .babelrc file in the root folder with the following content

```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "env": {
    "development": {
      "presets": [
        "react-hmre"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-react-remove-prop-types"
      ]
    }
  }
}
```

Worked after that.

More info on [.babelrc ](https://babeljs.io/docs/usage/babelrc/)
