### ISSUE TITLE
Express.js Config (Views)

### ISSUE THREAD

**Issue by jrodl3r** [choonkending/react-webpack-node#251]
I can't figure out these two lines in `config/express.js`
```
app.set('views', path.join(__dirname, '..', 'views'));
app.set('view cache', false);
```
Is this legacy code, or am I missing something? Thx!

+@choonkending

**Comment by choonkending** [comment]
Sorry about that and thanks for spotting this!

You're not missing anything! This brings me back to the good ol' days with `swig`. Hehe.

Would you like to create a PR for this?
