### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by caranicas** [choonkending/react-webpack-node#252]
Note: This is just a template, so feel free to use/remove the unnecessary things

- Type: Bug

**Expected Behavior**

`npm run dev` should start the dev server without any issues

**Actual Behavior**

```
sh: line 1: 78600 Segmentation fault: 11  npm run babel-node -- server/index.js
[nodemon] app crashed - waiting for file changes before starting...
```

**Steps to Reproduce**

So I upgraded to node 6, and that might be what is at the root of this, because I have been getting some other strange behavior, but occasionally when come back to my project and start it up I occasionally get this Segmentation fault error.

I did some Googling and found this [issue](https://github.com/nodejs/node/issues/2752) in the node repo, so I did what it said, and killed my modules and reinstalled. Which fixes it, but is a pain to have to do once or twice a day. Has any one else be having this issue?

**Comment by psimyn** [comment]
bumped kerberos (which was segfaulting for me)

`npm i` after grabbing this change and let me know if it is fixed

**Comment by caranicas** [comment]
ok ill pull the latest and keep you updated. Hopefully that should clean up the stack traces that keep clogging up my terminal.
