### ISSUE TITLE
ES6 Node

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#26]
Hey,

First of all love this application - it is a fantastic learning tool!

I have a quick question, is there a reason the node part of this app isn't wrote using ES6?

**Comment by choonkending** [comment]
@joshhornby Thanks for your feedback!! :) 

I didn't rewrite the node part in ES6 initially because it was not part of the webpack build step and I thought Heroku didn't support the node 0.12 runtime. 

But I'm happy to have the node end have a ES6 refactor. If you're interested, would you like to submit a PR for this?

**Comment by joshhornby** [comment]
I should have some time to ES6 the node side, although may need some help with the webpack build step.

**Comment by choonkending** [comment]
@joshhornby Sure thing! Thanks!

**Comment by SOSANA** [comment]
1+ be nice for people coming from ES5 to ES6 to see the difference. I will be hacking away with this. Be cool to have a branch for ES5 just for learning but understand the need to move forward with ES6.

**Comment by choonkending** [comment]
@SOSANA Thanks!

Yea I agree. I considered having separate branches for ES5 and ES6 when I made the ES6 change, but went ahead with just one branch and thought having docs for it would be good enough. 

I have a small README [here](https://github.com/choonkending/react-webpack-node/blob/master/docs/ReactInES6.md) for moving to ES6 from ES5 with React. If you like you can create a separate ES5 branch, or update that doc :)

**Comment by SOSANA** [comment]
@choonkending your so money, Just checked outed README. Good job! Hope to contribute when I can :)

**Comment by choonkending** [comment]
I've been using io.js to run npm.

We could go with node v0.12 with the --harmony flag (i think)

or io.js (which supports ES6 by default)

 @joshhornby what do you think? I'm leaning towards io.js. 

Heroku also supports this: https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

**Comment by joshhornby** [comment]
@choonkending I have no issues with switching to io.js.

Although whats the deal with io.js and node.js merging? I thought I heard discussions at one point?

**Comment by choonkending** [comment]
I'm using node 5 currently. Just haven't made the switch for the server side code. Should really look into this.

**Comment by caranicas** [comment]
the best example I have found using es6 on the server is the react starter kit from kriasoft. https://github.com/kriasoft/react-starter-kit

the way it uses webpack is and the build scripts is pretty different, so I am still trying to detangle it all, and figure out why the bable-loader isn't running on our server code.

**Comment by choonkending** [comment]
I reckon we should compile with `babel-cli` instead of the `babel-node` method being used in the react-starter-kit because we are aiming for production use. Read [babel-node](https://babeljs.io/docs/usage/cli/).
