### ISSUE TITLE
Unit Testing Stateless Components w/ Karma

### ISSUE THREAD

**Issue by jrodl3r** [choonkending/react-webpack-node#261]
Having trouble unit testing even the simplest of stateless components. Getting it to fail/not-render is no problem, just passing the rendering test w/ good array data.

Any gotchas that I might be missing on wiring-up tests for stateless component?

Thx

**Comment by choonkending** [comment]
Need to use react-stateless-wrapper for testing I believe

**Comment by jrodl3r** [comment]
**`/app/tests/components/MainSection-test.js`**

```
import { wrap } from 'react-stateless-wrapper';
import MainSection from 'components/MainSection';
import TopicItem from 'components/TopicItem';
...
const WrappedMainSection = wrap(MainSection);
...
describe('Has topics', () => {
    it('should render TopicItems', () => {
      result = ReactTestUtils.renderIntoDocument(<WrappedMainSection topics={topics} {...stubFunctions} />);
      topicItems = ReactTestUtils.scryRenderedComponentsWithType(result, TopicItem);
      expect(topicItems.length).toBe(1);
    });
  });
```

How would _this_ test work/change if the `TopicItem` component were stateless?

Thx

**Comment by choonkending** [comment]
You would need to wrap TopicItem in a `wrap`.

```javascript
const WrappedTopicItem = wrap(TopicItem);
```

Anything stateless in react needs to be wrapped in a component. 

We might consider moving towards [Enzyme](https://github.com/airbnb/enzyme) from airbnb in the future if we find this not a good idea.

**Comment by jrodl3r** [comment]
I get that it needs to be wrapped, but on this MainSection-test example, the `TopicItem` is being passed to `ReactTestUtils.scryRenderedComponentsWithType(result, TopicItem);` - If you change that `TopicItem` param to `WrappedTopicItem` the test fails.

I guess I'm asking how you can have a Karma test here where both the parent and child component being tested are stateless. Does that make more sense? Thx!

**Comment by jrodl3r** [comment]
Would love to setup a PR to add Enzyme support for UI testing... However, it's a little fuzzy for me as to how you would add Enzyme to the current testing configuration (along side the _actions_ and _reducers_ tests), while removing the current "wrap" system that is in place for testing UI and rendering.

Point me in the right direction and I'll be more than happy to take a shot, Thx!

**Comment by jrodl3r** [comment]
It works pretty well. But, still going to try to get **_TopicItem_** to `connect({ ...action-handlers... })` directly (instead of passing them through **_Vote_ » _MainSection_ » _TopicItem_**). Just need to figure out how the connect-stuff works w/ Enzyme... BRB 👻
