### ISSUE TITLE
Cleaner Code

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#263]
⚠️  This is a placeholder for me to list down the potential refactors we can do to clean up our code.

I will be adding more to this list + documenting them before working on it.

## Enhancement

**Simplifying code**
- Use ES6 for array.concat
```javascript
[...todos.slice(0, index),
 {todo},
 ...todos.slice(index+1)]
```
- Use ES6 for instead of Object.assign
```javascript
{...todos,
 {
   todo: 1
 }
}
```
- Reducer composition
```javascript
const topic = (state={}, action) {
     switch(action.type) {
         case CREATE_TOPIC_REQUEST:
               return {
                        id: action.id, count: action.count, text: action.text
                };
          default:
                return state;
     }
}

const topics = (state={}, action) {
        switch(action.type) {
           case  CREATE_TOPIC_REQUEST:
               return {
                    ...state.topics,
                    topic(undefined, action),
                    newTopic: ''
               };
            default:
               return state;
       }
}
```
where our topics can be composed with topic.

Explanation [here](https://egghead.io/lessons/javascript-redux-reducer-composition-with-arrays?course=getting-started-with-redux)

**Suggested enhancement**

**Pros**
- Cleaner

**Cons**
- None that I can think of

- Selectors

https://github.com/reactjs/reselect

**Comment by caranicas** [comment]
we are using `stage-0` in babel so we can use  the object spread operator as well instead of `Object.assign()`  its so clean

**Comment by choonkending** [comment]
https://medium.com/@kylpo/redux-best-practices-eef55a20cc72#.th7ljxfp0

*Use selectors everywhere!*

**Comment by choonkending** [comment]
Will create a separate issue when we use reselect. Closing for now.
