### ISSUE TITLE
pass router props to static need issue

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#268]
I am trying to fetch some user data based on a token from url like `mysite.com/w/:token` that leads to `WaitingListPage` component

```
export default class WaitingListPage extends React.Component {
  static need = {
    getWaitingListPosition(this.props.routeParams.token)
  }

  ...
}
```

however in this case `this.props.routeParams.token` results in error
> Unable to read props of undefined

Hence I wanted to ask how could I achieve this functionality?

**Comment by jrodl3r** [comment]
#248

**Comment by IljaDaderko** [comment]
Was able to achieve the task via:

```
this.props.router.push({
  pathname: '/example-route',
  query: { showMenu: true }
})
```

**Comment by vierja** [comment]
@IljaDaderko can you explain a bit more on how you were able to achieve that using that code? I'm having the same issue.
