### ISSUE TITLE
Where is the universalRenderer in app/app.js imported to?

### ISSUE THREAD

**Issue by gsccheng** [choonkending/react-webpack-node#27]
Hi, in trying to understand the flow of the app, I came upon the app/app.js file where the universalRenderer is exported per below:

```
export default universalRenderer(alt, routes, html);
```
However, I am unable to find what file actually imports it. I did a search but wasn't able to find anything. Is the universalRenderer only executed on the client-side after it's built or minified or something?

Thanks!

**Comment by psimyn** [comment]
webpack config creates 2 versions of this: app.js and app.server.js

The server rendered one is included in ```server/config/routes.js``` on the server side. This takes the HTML of ```app/base.html```, which includes the client-rendered app.js in a script tag.

**Comment by gsccheng** [comment]
Oh ok, looks like the `export` function is necessary for Webpack to pick it up properly-- I'm guessing it is translated to one of these strange lines like this `exports['default'] = UniversalRenderer;` which is somehow used in app.server? I was just used to every `export` of a file be complemented by an `import` in another file to actually use it.

**Comment by choonkending** [comment]
@gsccheng Yep!
[Webpack](http://webpack.github.io/docs/what-is-webpack.html) bundles the entire App, and because I'm exporting it as a function, we supply it arguments to be used [here](https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L74)

```javascript
// Import the webpack emitted bundle
var App = require('../../public/assets/app.server');
// ...
// Passing in data to bootstrap our alt Stores and url for react-router
var html = App(JSON.stringify(res.locals.data || {}), req.url);
```

Hope that helps.

**Comment by gsccheng** [comment]
Thanks guys for your quick responses and concern! It truly feels good to know that there are people there to help, especially when you may be a bit shy broadcasting out into the world, and tackling something complicated (at least for me).

@choonkending What I meant was more about the export of `universalRenderer(alt, routes, html);` in `app/app.js`, (not the export of `../../public/assets/app.server`). Nothing seemed to explicitly `import` that `app/app.js` file. Yet, this is okay because Webpack still bundled it and `universalRenderer(alt, routes, html);` is still used.

It looks like it is because in `webpack.config.js` we have this section
```
    name: "server-side rendering",
    context: path.join(__dirname, "app"),
    entry: {
      app: "./app",
      header: "./elements/Header.react"
    },
    target: "node",
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: "[name].server.js",
```
that essentially imports it, specifically through `app: "./app",`. There's also the equivalent section in this config file to produce the `app.js` output for the client side. Is this correct?

**Comment by choonkending** [comment]
@gsccheng Spot on! :)

**Comment by choonkending** [comment]
@gsccheng I'm closing this issue. If you have any questions, feel free to open another one or join our Gitter room!
