### ISSUE TITLE
Unable to use static need ... build error + eslint error

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#276]
Bellow is a stripped down code for one of my container components that needs to fetch some api data before rendering. I used static need as shown in this example: https://github.com/choonkending/react-webpack-node/blob/master/app/containers/Vote.jsx however am getting an es-lint error despite the disable comment and when I try to run `npm run dev` I get following error:

> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "babel-node" "--" "server/index.js"
> npm ERR! node v6.2.1
> npm ERR! npm  v3.9.5
> npm ERR! code ELIFECYCLE
> npm ERR! loot-io@0.1.0 babel-node: `babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the loot-io@0.1.0 babel-node script 'babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the loot-io package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs loot-io
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls loot-io
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/ilja/Documents/Repositories/loot.io/npm-debug.log

**my code**
NOTE: I'm not sure if I'm allowed to use static inside constructor, but I need access to a token props from react router params. That, said I tried placing my static need right after `export default class WaitingListPage extends React.Component {` line, it got rid of es-lint error, but npm build error still stayed event when token was replaced to a sting instead of `this.props.routerParams.token`.

```
function mapDispatchToProps (dispatch) {
  return bindActionCreators({
    getWaitingListPosition
  }, dispatch)
}

@connect(null, mapDispatchToProps)
export default class WaitingListPage extends React.Component {

  constructor (props) {
    super(props)
    this.state = {
      /* ... */
    }
    static need = [  // eslint-disable-line
        this.props.getWaitingListPosition(this.props.routerParams.token)
    ]
  }

/* ... */

  render () {
    return (
      <div className={cx('WaitingListPage')}>
        <Header />
        <main>
          <div className={cx('WaitingList-Wrapper')}>
            <div className={cx('WaitingList-Content', 'container-fluid')}>
              {this.props.routeParams.token ? (
                <WaitingListPosition refCode='DEMO0989' />
              ) : null}
            </div>
          </div>
          {this.props.routeParams.token ? (
            <div className={cx('WaitingList-Confetti')}>
             { /* ... */ }
      </div>
    )
  }
}
```

`EDIT:` I believe I was able to make it through to middleware, by changing my code to not map getWaitingListPosition to the props and moving static need out of constructor, so my component now becomes:

```
export default class WaitingListPage extends React.Component {
    static need = [  // eslint-disable-line
        getWaitingListPosition(`someToken`)
    ]

/* ... */
}
```

However I now get following error:

> TypeError: need is not a function

I believe it is referring to `app/middleware/preRenderMiddleware.js` where it dispatches need function.

**Comment by IljaDaderko** [comment]
Possible issue is that passing (`someToken`) param actually invokes the function and hence need is a promise, but not a function afterwards, but I can't find a way around it.

**Comment by IljaDaderko** [comment]
Was able to sort it pout, you can simply use getWaitingListPosition function and inside your actions have access to params passed by middleware, hence access token through something like `params.token`

**Comment by yowakita** [comment]
@IljaDaderko Can you explain a little about the params passed by the middleware that you mention above? I am have trouble getting a fetch to work when I need a property from the store such as an ID of an object. How do you pass the params to the middleware, and how to you access it inside the action?

**Comment by unkleho** [comment]
Hi, I think this is what @IljaDaderko means:

```
export default class WaitingListPage extends React.Component {
    static need = [  // eslint-disable-line
        getWaitingListPosition() // Don't pass token here
    ]

    /* ... */
}

// in routes.jsx
/* ... */
<Route path="/waiting-list/:token" component={WaitingListPage} />
/* ... */

// in actions
export function getWaitingListPosition(params)  {
    return {
        type: GET_WAITING_LIST_POSITION,
        promise: makeRequest('get', params.token) // token accessible via params
    }
}
```

preRenderMiddleware.js passes the whole params object to every action in the 'need' array.

Hopefully this makes sense - I was struggling with the same issue and this workaround seems like it should work.

This issue is similar: https://github.com/reactGo/reactGo/issues/281

Been enjoying working with ReactGo btw, thanks to everyone.

**Comment by yowakita** [comment]
@unkleho That does clarify a bit for me. 

Thank you for the advice, if I find any insight that is useful for others, I will post here.
