### ISSUE TITLE
Socket.io Route Warning

### ISSUE THREAD

**Issue by drosko** [choonkending/react-webpack-node#28]
When I run 'npm start' I get endless warnings of "No route matches "/socket.io/?EIO=3&transport=polling&t=XXXXXXXXXXX-XXXXX". Make sure you have <Route path="/socket.io/?EIO=3&transport=polling&t=XXXXXXXXXXX-XXXXX" somewhere in your routes. Any idea why this would be happenning?

**Comment by joshhornby** [comment]
Wouldn't having a '.' in url cause this issue? Have you tried ```/socketio/etc```

**Comment by drosko** [comment]
Probably, but I don't even know where it's coming from. Haven't made any changes to the repo, just cloned and ran it.

**Comment by choonkending** [comment]
@drosko Thanks for letting us know.

Socket.io was an old dependency used in the repo and I removed it a while ago.

Could you try pulling the latest master and npm install again ? (That will compile the bundle again)

Let me know how that goes. :)

**Comment by drosko** [comment]
Ok great thanks, seems to not be happening anymore now,
