### ISSUE TITLE
Placing files in server root

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#283]
I am trying to implement [Universal Links](https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html) that should be pretty straight forward. It simply requires me to put a specific .json file in the root directory of my app. I'm having trouble figuring out what it is in this starter pack, does it refer to /public folder?

**Comment by psimyn** [comment]
yep, public folder.

If you wanted to set a custom path you can resolve from server/config/routes.js
