### ISSUE TITLE
'id' created clientside, mongodb '_id' ignored?

### ISSUE THREAD

**Issue by InstanceOfMichael** [choonkending/react-webpack-node#29]
What's the reason for this?

**Comment by choonkending** [comment]
@InstanceOfMichael 

Thanks for asking. 

We're going with the optimistic updates approach, so we create the `id` on the clientside -> send the request and update the view. Waiting for the server to respond with the mongodb `_id` generated will be a bad experience for the user imo. 

So we're *assuming* that the update is successful first, and only update the UI to reflect the error if the request fails (I have not added this part in). 

I think it is a bit redundant and confusing to have `id` and `_id`.

My understanding is that mongodb automatically generates the `_id` when we insert a topic. So we could either:
1. Set autoindex to `false`
2. Replace id to become _id when sending to the server

Did I answer your question? Also, if you have a good solution to this, would you like to submit a PR for this?
