### ISSUE TITLE
Minor Production Tweaks

### ISSUE THREAD

**Issue by jrodl3r** [choonkending/react-webpack-node#290]
3 small things...

**1. Redux DevTools is currently accessible on PROD**
Adjusted the _DEVCLIENT_ case in `configureStore.js`:
```javascript
  let store;

  if (__DEVCLIENT__) {
    middleware.push(createLogger());
    store = createStore(rootReducer, initialState, compose(
      applyMiddleware(...middleware),
      typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ? window.devToolsExtension() : f => f
    ));
  } else {
    store = createStore(rootReducer, initialState, compose(applyMiddleware(...middleware), f => f));
  }
```

**2. Cheaper Source Maps**
Changed `devtool: 'source-map'` to 'cheap-module-source-map' in `webpack.config.prod.js` to reduce sourcemap size (see below).

**3. Arbitrary Vertx Build Message**
Added `new webpack.IgnorePlugin(/vertx/),` to webpack DEV/PROD server plugins to hide warning:
```
WARNING in ../~/es6-promise/dist/es6-promise.js
    Module not found: Error: Cannot resolve module 'vertx'
```

What are your thoughts @choonkending?

**Comment by ZeroCho** [comment]
wow, I didn't notice that Redux DevTools is accessible on PROD. Thanks @jrodl3r

**Comment by caranicas** [comment]
@jrodl3r Those all sound good to me. that vertx warning had been annoying.

**Comment by jrodl3r** [comment]
<img width="406" alt="screen shot 2016-06-28 at 5 22 45 pm" src="https://cloud.githubusercontent.com/assets/869411/16438934/70e3a3a2-3d68-11e6-89a5-1e8f49d1d123.png">

**Comment by choonkending** [comment]
@jrodl3r Champion! I'll review this now!
