### ISSUE TITLE
The code "require('postcss-mixins')()" is not in webpack.config.dev-client.js

### ISSUE THREAD

**Issue by ZeroCho** [choonkending/react-webpack-node#291]
Any reason `require('postcss-mixins')(),` is not included in **webpack.config.dev-client.js**, while **webpack.config.prod.js** has it?

**Comment by jrodl3r** [comment]
...🙈

**Comment by choonkending** [comment]
@ZeroCho Thanks for pointing that out. I must have removed it from `client` some time ago, as there were no mixins used in the boilerplate. Would you like to add it back in a pull request? 👍
