### ISSUE TITLE
Webpack dev server

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#33]
Just wondering if anyone has successfully managed to set up a [webpack-dev-server] (http://webpack.github.io/docs/webpack-dev-server.html) for this project?

**Comment by choonkending** [comment]
@joshhornby Thanks for asking! We haven't set it up yet but it's on our to-do list. Was hoping for dev server and React hot loader to speed up dev work. 

Would you be interested in working on this? I'll bump this up in priority. :)

**Comment by joshhornby** [comment]
I was hacking around earlier and could get webpack-dev-server to work with hot loading but my issue was I didn't know how to run the ```server/index.js``` in webpack. Any ideas @choonkending

**Comment by choonkending** [comment]
None yet, (was reading more about webpack-dev-server on the tram to work) :) If you have a branch up I can have a look!

**Comment by joshhornby** [comment]
I have pushed up what I have. https://github.com/choonkending/react-webpack-node/pull/34 We just need to get the node app into the webpack config and it should work.
