### ISSUE TITLE
PassportJS and production :(

### ISSUE THREAD

**Issue by anthonychung14** [choonkending/react-webpack-node#357]
### Description
- Type: Bug | Question
- Related Issue: `#production troubles`

---------------------------------------------------------------
## Bug
**Expected Behavior**
After configuring NGINX reverse proxy with SSL, I still cannot get Oauth to work.
Session ID is assigned and Oauth provider gives the profile

**Steps to Reproduce**
Try deploying via digital ocean, ubuntu 14.04, with HTTPS

**Comment by bring2dip** [comment]
@anthonychung14  where have you configured your ssl config? on the node app or in the NGINX server. if you have configured the ssl in the nginx server then you should set the session cookie secure to false in express config.

**Comment by anthonychung14** [comment]
@bring2dip configured SSL in reverse proxy NGINX
this has fixed my problem thank you
