### ISSUE TITLE
Unable to Log in properly with Google

### ISSUE THREAD

**Issue by gsccheng** [choonkending/react-webpack-node#36]
Hi, I cloned a fresh copy from Master and after installing the dependencies I am unable to log in with Google.

From the `login` route, after clicking the green "Login with Google" button, I am redirected to the index page where the "Log in" button is still present in the Nav Bar.

On that note, are you working on a test suite? Do you have a list of priorities for new features published? Maybe I can help, I started modeling one after another Alt-Flux boilerplate using Chai/Mocha/Karma.

**Comment by choonkending** [comment]
@gsccheng Hey thanks for asking!

You might have to export the variables:

```javascript
export GOOGLE_CLIENTID=YOUR_CLIENTID export GOOGLE_SECRET=YOUR_SECRET
```

This will also involve setting Google Authentication. You can follow the steps [here](https://github.com/choonkending/react-webpack-node/blob/master/README.md#setting-up-google-authentication)

Read more [here](https://github.com/choonkending/react-webpack-node#setting-up-google-authentication).

I have not yet created an actual list apart from this simple one [here](https://github.com/choonkending/react-webpack-node/blob/master/README.md#todo) in the README. 

Currently the features being actively worked on are:
1. React-hot-loader
2. CSS loader

The testing suite isn't part of it, but I've had discussions with @psimyn to add them in, and created an issue for this a while ago https://github.com/choonkending/react-webpack-node/issues/16

Any help is welcome!!

**Comment by gsccheng** [comment]
Ah sorry, missed that! I thought the variables would have been read anyways through the `||` operator since you directly included your tokens/info in your secrets file. If I have anything for the tests I'll make a pull request. Thanks for all the hard work!

**Comment by choonkending** [comment]
Thanks! :+1
