### ISSUE TITLE
[Help]Routing and logging in/out 

### ISSUE THREAD

**Issue by kkotwal94** [choonkending/react-webpack-node#38]
So I decided to hack away at this boilerplate and thought of it as a great opportunity to learn react router and flux. I have a couple questions that have me stumped though. I get the express js/node code pretty decently. I know that we are setting up our routes for logging in and out, but where I get confused is at React Router. 
What im trying to do is Have a Log In page, a Sign up page. The login and signup work fine, they just perform whatever was written in express using passport. However what I want to do is make a route '/dashboard'. I did so and it's just a dashboard component made up of other components like a navbar and body/content. <strong>How do I write it in react router in such a way that it only allows me to access the route /dashboard if the user is authenticated</strong>. In express I would write a function like this : 

```
function isLoggedIn(req, res, next) {
   //if user is authenticated in the session, carry on
   if (req.isAuthenticated())
      return next(); //cuz we want to move on incase we're stuck here

   //if they arent redirect them to the home page
   res.redirect('/');
}
```

However I didn't even write in the dashboard route in express. I only did it in react-router. My component hierarchy is like this right now
```
<App/>
  <Dashboard/>
     <NavBar/>
         <NavMenu/>
      <Body/>
  <Login/>
  <Signup/>
  <About/>
```

And my routing is like this : 
```
const routes = (
<Route>
 <Route name ="signup" path="/signup" handler={Signup} />
 <Route name ="login" path="/" handler={Login} />
 <Route name ="app" path="/dashboard" handler={App} >
  <Route name ="logout" path="/logout" handler={NavMenu} />
 </Route>
</Route>
	);
```
I don't understand if i'm grasping the concept right, but from what the webpage is displaying it doesn't seem like it. So basically at localhost:3000/ comes up the log in page, and I can toggle between that and the signup page completely fine, when the log in button is hit it uses express to login (it can use react-router to do it as well correct?), on success it goes to /dashboard (res.redirect('/dashboard') in express). It also seems as routes handled by react router has that single page app feel, whereas express it feels like i'm going to a new webpage (I'm guessing that happens because of react-router just changing the url and rendering the component we want?). In my NavMenu component I link the logout button <Link to=logout>Logout</Link> however the url changes to localhost:3000/logout and nothing happens.  

I want to maintain that react-router web feel instead of that express redirect but im struggling and looking for help. :/ 

The github for this repository is <a href =https://github.com/kkotwal94/IsoReportProcessor>Here </a>

**Comment by kkotwal94** [comment]
Ok so I kinda understand how it works now, handler renders whatever we import, and and I changed the way my structure works as well.
```
<App>
 <Navbar >
   <NavMenu>
      <li className="cd-selected">
        <Link to="dashboard">Dashboard</Link>
      </li>

      <li>
        <Link to="reports">Reports</Link>
      </li>

      <li>
        <Link to="employees">Employees</Link>
      </li>

      <li>
        <a href="/logout">Logout</a>
      </li>

      <li>
        <Link to="addReport">Create New Report</Link>
      </li>
    </NavMenu>
 <RouteHandler />
```

Where my router is.. 
```
<Route>
 <Route name ="signup" path="/signup" handler={Signup} />
 <Route name ="login" path="/" handler={Login} />
 <Route name ="dash" path="/dashboard" handler={App}>
    <Route name ="dashboard" path="/dashboard" handler={Dashboard}/>
    <Route name ="reports" path="/reports" handler={Report} />
    <Route name ="employees" path="/employees" handler={Employees} />
    <Route name ="addReport" path="/addReport" handler={AddReports} />
 </Route>
</Route>
```

I don't know if I did the "dash" one correctly, but its working, on login it redirects to /dashboard in the express server, /dashboard is filled with {App} and app does its thing.

However I would still like to understand how to do logout in react router rather than express. When I add 

```
<Route name ="logout" path="/logout" />
```
and then add the Link in the NavMenu, it just takes me to /logout rather than performing the same action as it would in the express server if it was at that route. I think my misunderstanding lies in that I thought by setting a route in react-route it would behave just as the one in my express server, idk If i even said that with any type of sense.

**Comment by choonkending** [comment]
@kkotwal94 Hey thanks for commenting!

It feels like your question is more regarding how [react-router](https://github.com/rackt/react-router) works.

I added a [Logout action to my link](https://github.com/choonkending/react-webpack-node/blob/master/app/components/Navigation.react.js#L39), and made an API call to the /logout endpoint via Ajax (behind the scenes).

Does that help? Haha :)

**Comment by kkotwal94** [comment]
Yea it does, sorry for missing the obvious I totally skipped over the UserAPI. I was wondering how we were binding the data to the front end. I finally figured out how react-router, now im trying to figure out how flux works and writing react in es6.

**Comment by choonkending** [comment]
No worries. It might be a bit confusing at first, but now that I use the flux design pattern and es6, I can't go back!
