### ISSUE TITLE
Localstorage/session storage and persistence

### ISSUE THREAD

**Issue by kkotwal94** [choonkending/react-webpack-node#39]
Why is it when I run the heroku demo, I can refresh and still be logged in whereas when I run it on localhost the data/stores also refresh. Does persistence not work with localhost? It seems like my session ID won't save either as a cookie.

**Comment by kkotwal94** [comment]
You can close this, thanks for the helpful comments in the files. I realized that the secure setting under cookie was on, therefore it wouldnt work on anything over https

**Comment by choonkending** [comment]
Sure thing :) closing issue.
