### ISSUE TITLE
[Question] How to get user data after manual login

### ISSUE THREAD

**Issue by slavab89** [choonkending/react-webpack-node#396]
Hi,
So i'm trying to get something to work and understand it at the same time.
In the server.jsx file there is kinda of a SSR handling if i understood correctly - when reloading the page in the browser it gets there and i can access the req object and get the user data from req.user (that is being populated by Passport)
But what happens when i perform a manual login? I get redirected to the homepage but i dont know how to access the req.user data. Can i even access it? How should i get the logged in user data?

**Comment by ZeroCho** [comment]
You should send user object instead of message [here](https://github.com/choonkending/react-webpack-node/blob/master/server/db/mongo/controllers/users.js#L19)
Then you can access user object as action.result in LOGIN_SUCCESS reducer

**Comment by slavab89** [comment]
Right. Thought that this would be the correct approach in the end.
Wondered if there is something else that i'm missing on the client side =]

Thanks!!
