### ISSUE TITLE
React Router not handling URLs with slashes 

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#40]
There seems to be an issue with URLs with slashes.

For example if you try 

```
<Route name="about/us" handler={About} />
```

You will receive the following error 

```
Warning: No route matches path "/about/us". Make sure you have <Route path="/about/us"> somewhere in your routes
Warning: No route matches path "/about/assets/styles/main.css". Make sure you have <Route path="/about/assets/styles/main.css"> somewhere in your routes
Warning: No route matches path "/about/assets/app.js". Make sure you have <Route path="/about/assets/app.js"> somewhere in your routes
```

The full ```routes.js``` file is here

```
import React from 'react';
import { Route, DefaultRoute } from 'react-router';

import App from 'components/App.react';
import Vote from 'components/Vote.react';
import About from 'components/About.react';
import Login from 'components/Login.react';
import Logout from 'components/Logout.react';

const routes = (
  <Route name="app" path="/" handler={App}>
    <Route name="login" handler={Login} />
    <Route name="logout" handler={Logout} />
    <Route name="vote" handler={Vote} />
    <Route name="about/us" handler={About} />
    <DefaultRoute handler={Vote} />
  </Route>
);

export default routes;
```

Not sure what might be causing this? Something to do with express or node?

**Comment by psimyn** [comment]
change `name="about/us"` to `path="about/us"`

**Comment by psimyn** [comment]
@choonkending possibly worth changing all the routes to use path? I'm not sure of the purpose of name in routes

**Comment by joshhornby** [comment]
@psimyn Ah yes! How stupid of me! Thanks

**Comment by choonkending** [comment]
@psimyn Thanks. Had a look [Route API](http://rackt.github.io/react-router/#Route). I'll give it a test tomorrow. Definitely worth changing.

**Comment by joshhornby** [comment]
@psimyn @choonkending Seems that there is an issue on refresh, for example if I have ```<Route name="about" path="about/us" handler={About} />``` and I go to the page from the nav bar it works, but if I was to go to the page directly http://localhost:3000/about/us I'd get the following errors:

```Warning: No route matches path "/about/us". Make sure you have <Route path="/about/us"> somewhere in your routes
Warning: No route matches path "/about/assets/styles/main.css". Make sure you have <Route path="/about/assets/styles/main.css"> somewhere in your routes
Warning: No route matches path "/about/assets/app.js". Make sure you have <Route path="/about/assets/app.js"> somewhere in your routes```

**Comment by psimyn** [comment]
@joshhornby check your path again :)

missing leading slash

**Comment by joshhornby** [comment]
```<Route name="about" path="/about/us" handler={About} />```

Same error.

```Warning: No route matches path "/about/assets/styles/main.css". Make sure you have <Route path="/about/assets/styles/main.css"> somewhere in your routes
Warning: No route matches path "/about/assets/app.js". Make sure you have <Route path="/about/assets/app.js"> somewhere in your routes```

**Comment by choonkending** [comment]
This seems like an issue with react router not finding the correct handler
on the server. Might because the name is different from path.

Also could you try pulling the latest changes? The other warnings should
not appear now because I fixed the source map issue.

**Comment by choonkending** [comment]
Also is there a reason why you have /about/us? It normally suggests that
there is a nested route.

I would normally name it /about-us :)

**Comment by joshhornby** [comment]
@choonkending Just an example to illustrate to bug more than anything.

**Comment by choonkending** [comment]
Ahh I see. Lol sorry about that. I thought I should call that out in case
you were doing that in production hehe.

I'll try to replicate your issue later and give you feedback

**Comment by choonkending** [comment]
@joshhornby 

`<Route name="about" path="/about/us" handler={About} />` shouldn't have a problem. I don't think the issue is this. I used `<Route name="about" path="about/us" handler={About} />` and it worked for me. 

I could access the page, but I needed to put a leading slash in my `src` in `base.html`

```javascript
<script type="text/javascript" charset="utf-8" src="/assets/app.js"></script>
```

Also needed to change `"rel": "stylesheet", "href": "/assets/styles/main.css"` in `helmconfig.js`.

@psimyn I read a bit more in [router docs - this section](http://rackt.github.io/react-router/#Route).

We need the `name` in Route for `<Link to="name"></Link>`. Also makes more sense for semantic reasons.

Also, [react-router beta](https://github.com/rackt/react-router/tree/v1.0.0-beta1) is out! Rejoice!

**Comment by joshhornby** [comment]
Perfect this seemed to fix it :+1: thanks @choonkending
