### ISSUE TITLE
Restricted areas for certain parts of the app

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#41]
I am using this boilerplate as the base for a project I am currently working on. 

Once a users has logged out I want to stop them being able to access certain areas of the app, for example a ```<Dashboard />``` component.

Do you know of a nice way to do this?

**Comment by choonkending** [comment]
Good question. When I did this the last time, I had a UserStore on the
Navigation Component that hid the links if the user was not authenticated.
The dashboard component  and endpoint should also redirect to the login
page if they accessed directly.

I'll have a think to see if there is a better way about this. :)

**Comment by choonkending** [comment]
@joshhornby For reference I did [this](https://github.com/choonkending/reap/blob/master/app/components/Navigation.react.js) the last time when trying  to connect with postgresql database. That was a different repo based off this one.

It hides the Links if the user is not logged in. However, there is still additional work to do if you want it to handle users who go to the link directly, i.e. `/dashboard` directly.

For example, in the React Component you might need to test if the user is authenticated, and if not, `transitionTo` to a `/login` page. Read more [here](http://rackt.github.io/react-router/#Navigation). 

I think this should work, but I haven't tested this on the isomorphic (universal) js app. Let me know how this goes, would be interesting to have that as part of the example.
