### ISSUE TITLE
duplication in webpack configs

### ISSUE THREAD

**Issue by psimyn** [choonkending/react-webpack-node#42]
client / server configs share most options, so can have a common set and just override things like `target` as needed.

maybe need a common.config imported by webpack config and dev-server config

**Comment by choonkending** [comment]
Agreed. We can have a make-webpack-config that I've seen around. I didn't
do it for hot loader cause I thought it might be overkill. It s definitely
worth doing.

:+1

**Comment by choonkending** [comment]
@psimyn Don't think it's a huge issue, I'm quite happy actually keeping them separate, as it makes it easier to understand. Please reopen if you disagree :D
