### ISSUE TITLE
Create a Yeoman generator

### ISSUE THREAD

**Issue by lachlanjc** [choonkending/react-webpack-node#44]
It'd be pretty awesome to have this as a [Yeoman](http://yeoman.io/) generator :)

**Comment by choonkending** [comment]
@lachlanjc Excellent suggestion. I've been skirting around this issue for a bit, never got around to it :P 

Are you interested in creating a PR or working with us on this one? :D

**Comment by lachlanjc** [comment]
@choonkending I'd love to, but I've never made a generator. I was just introduced to Yeoman a few days ago, and started looking around for generators. This project looked pretty close to the stack I wanted for a new project, but was disappointed there was no Yeoman generator. However I have no idea how to create one, so I can't really PR 😁

**Comment by choonkending** [comment]
@iiegor This works great! Really good work dude! Thanks for all the hard work!

I think this PR deserves it's own repository! I'm happy for you to create and publish (and I will link it from the README). The reason for this is I think it would be easier (and less confusing) to have the generator code separate + easier to maintain.

Users who come to this repo will then have the chance to either:
1. `clone` it and use it
2. Use the generator to run the necessary components.

What do you think?

**Comment by iiegor** [comment]
I totally agree with you @choonkending. All done, check [iiegor/generator-react-webpack-node](https://github.com/iiegor/generator-react-webpack-node) :+1:

**Comment by choonkending** [comment]
Updated README https://github.com/choonkending/react-webpack-node/commit/98c2865d8606fce8ca93f7e3a0808ed880718284

**Comment by choonkending** [comment]
Closing issue. @iiegor Thank you so much for your hard work!
