### ISSUE TITLE
Session variables not available in topics.js

### ISSUE THREAD

**Issue by sijo-vijayan** [choonkending/react-webpack-node#45]
I don't getting session data in the topics.js page, How to fix it ?

**Comment by choonkending** [comment]
@sijo-vijayan Thanks for commenting! 

I need a bit more context on the error you are getting, i.e.

1. What are the error messages you are getting?
2. How are you running it? (Locally?)
3. Can you list down the steps to reproduce this error?

**Comment by sijo-vijayan** [comment]
No errors, But i need to get the session variables such as user id, e-mail, name etc from the passport.js session. I have tried the  "req.user" property to get this data , but no use. I have tried the changes in code  as given in this 
url http://passportjs.org/docs/#middleware

I just want a login protected page 
I hope you understand what i'm talking about.

Thanks

**Comment by choonkending** [comment]
@sijo-vijayan I don't think we have login protected pages within this boilerplate currently but we are planning on adding that in, created an issue for that https://github.com/choonkending/react-webpack-node/issues/47. 

You should be able to access `req.user` like how we do so https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L62.

**Comment by choonkending** [comment]
@sijo-vijayan I think I'm encountering the same problem as you. I'll look into this now and see what's causing the issue.

**Comment by choonkending** [comment]
https://github.com/choonkending/react-webpack-node/commit/46f7cb0184668b2fbd77c186f9b3b5bd52f30c33

should probably give you access to `req.user` now.

**Comment by sijo-vijayan** [comment]
Wow !!!, Now it is working properly. 
Thanks you @choonkending
