### ISSUE TITLE
failure to fetch data sometimes, or route not loading

### ISSUE THREAD

**Issue by kkotwal94** [choonkending/react-webpack-node#46]
I don't know how to debug this exactly or where to start. When ever I traverse through routes in my single page app sometimes going back to the route the server stops responding and doesn't fetch any data to present to the app. I thought it was my routes at first but I'm not sure where to start or even look at. Is it maybe something to do with my API, could too many ajax calls be getting called? Any advice? The strange thing is, on chrome hitting refresh it will say 'Waiting for localhost..' and on firefox it will refresh normally.

**Comment by choonkending** [comment]
@kkotwal94 Hmm. Do you have some code for us to look at and some reproducible steps? I think I get what you're saying but if you have something I can reproduce reliably it can really speed up our debugging process. :D

**Comment by kkotwal94** [comment]
Yea, I'm not sure if this is it. Here was how I reproduced it, between the route /reportsall and reports/:id i just spammed back and forward buttons (alt+right, alt+left) and I kept doing it until it would just say undefined where the data should be. I can hit refresh but it will state waiting for localhost and take a lot longer than usual to refresh. On Firefox this issue will not ever happen, same with IE. I can start with this, maybe this will give an idea:

Here is the handler: for /reportsall
```
https://github.com/kkotwal94/IsoReportProcessor/blob/master/app/components/Report.js
```

Here is the handler for /reports/:id
```
https://github.com/kkotwal94/IsoReportProcessor/blob/master/app/components/ReportView.js
```

they are both similar. I console.logged to make sure the data was being obtained and it was @ ReportView however the view presented undefined. The console data showed everything that was supposed to be loaded however.

Here is my route Overview, might be the problem on how I set this up too:

```
import React from 'react';
import { Route, DefaultRoute } from 'react-router';
import App from 'components/App';
import Login from 'components/Login';
import Signup from 'components/Signup';
import Dashboard from 'components/Dashboard';
import Report from 'components/Report';
import Employees from 'components/Employees';
import AddReports from 'components/AddReports';
import AllEmployees from 'components/AllEmployees';
import MyEmployees from 'components/MyEmployees';
import Profile from 'components/Profile';
import ReportsToComplete from 'components/ReportsToComplete';
import Readme from 'components/Readme';
import Stats from 'components/Stats';
import NewReport from 'components/NewReport';
import TemplateReport from 'components/TemplateReport';
import ReportView from 'components/ReportView';
import EditReport from 'components/EditReport';
import AssignReport from 'components/AssignReport';
import AssignReported from 'components/AssignReported';
import AddSubreport from 'components/AddSubreport';
import NotFound from 'components/NotFound';
import ReportHandler from 'components/ReportHandler'
import Index from 'components/Index';
import { history } from 'react-router';

const routes = (
<Route>
 <Route name ="dashboard" path="/dashboard" handler={App}>
    <Route name ="dash" path="/dashboard" handler={Dashboard}/>
    <Route name ="assignReport" path="/user" handler={AssignReport}/>
    <Route name ="assignReported" path="/user/:id" handler={AssignReported}/>
    <Route name ="employees" path="/employees" handler={Employees}/>
    <Route name ="reports" path="/reports" handler={ReportHandler}>
      <Route name ="report" path="/reportsall" handler={Report}/>
      <Route name ="singlereports" path=":id" handler={ReportView}/>
      <Route name ="addsubreport" path=":id/addsubreport" handler={AddSubreport}/>
      <Route name ="editreports" path=":id/edit" handler={EditReport}/>
    </Route>
      <Route name ="MyEmployees" path="/MEmployees" handler={MyEmployees}/>
      <Route name ="AllEmployees" path="/AEmployees" handler={AllEmployees}/>
      <Route name ="Profile" path="/profile" handler={Profile}/>
      <Route name ="reportstocomplete" path="/reportsc" handler={ReportsToComplete}/>
    <Route name ="addReport" path="/addReport" handler={AddReports}/>
    <Route name ="readme" path="/readme" handler={Readme}/>
    <Route name ="statistics" path="/statistics" handler={Stats}/>
    <Route name ="signup" path="/signup" handler={Signup} />
    <Route name ="newreport" path="/newreport" handler={NewReport}/>
    <Route name ="templatereport" path="/templatereport" handler={TemplateReport}/>
    <Route name ="404" path="/404NotFound" handler={NotFound}/>
    <Route name ="login" path="/" handler={Login}/>
 </Route>
</Route>
	);

export default routes;

```
I set this up differently a lot of times, and it occurred however I adjusted my routes, I don't think this is the issue though.

**Comment by kkotwal94** [comment]
I'm starting to think this is a ajax call thing, and how im writing my API, will try some stuff out and reply back later!
