### ISSUE TITLE
Hitting refresh on nested routes

### ISSUE THREAD

**Issue by kkotwal94** [choonkending/react-webpack-node#50]
I have my routes set up in a way where nested routes exist. When hitting refresh on non nested routes it loads the stores and html fine with this: 

```
app.get('*', function (req, res, next) {
    
    var html = App(JSON.stringify(res.locals.data || {}), req.url);
    html = html.replace("TITLE", Header.title)
                .replace("META", Header.meta)
                .replace("LINK", Header.link);

    res.contentType = "text/html; charset=utf8";
    res.end(html);
  });
```
So I decided to mess with a bit and try to understand why none of the css or data was loading on the refresh of nested route that is dynamic (based off '/x/:id') so I decided to do something like this. 
```
app.get('*', function (req, res) { 

    Router.run(routes, req.path, function (Handler, state) {
        var element = React.createElement(Handler);
        var html = React.renderToString(element);
        res.render('main', { content: html });
    });
});
```
<strong>I just wanted to know if what was written in the boilerplate was supposed to deal with nested routes, if so I'll know my problem lies elsewhere. I haven't tested this yet, because I have to require my 'route' here on the server as well. I also have little idea of what is going on in the boilerplay app.get(*)</strong>

**Comment by joshhornby** [comment]
On a separate but somewhat related note I am having issues with the render as well - I am trying to create a protected route following something like this http://www.aaron-powell.com/posts/2015-06-08-implementing-security-in-react-with-react-router.html

But my ```willTransitionTo``` method is failing with the following error ```Error: Unhandled aborted transition! Reason: [object Object]``` 

I have found a package that will solve this error https://github.com/ericclemmons/react-router-server-location but it will mean using a more decoupled router like the one above. I can create a separate issue for this is you like?

**Comment by choonkending** [comment]
@kkotwal94 the boilerplate was meant to deal with nested routes initially, but I'm not sure it applies in your case. I'll have a look after I finish the protected routes feature #47 and get back to you on that :)

**Comment by kkotwal94** [comment]
Sure I'm going to continue to debug and figure it out, and thanks.

**Comment by kkotwal94** [comment]
```
app.get('*', function (req, res) { 

    Router.run(routes, req.path, function (Handler, state) {
        var element = React.createElement(Handler);
        var html = React.renderToString(element);
        res.render('main', { content: html });
    });
});
```
I tried to run this on the server, but I always thought UniversalRender took care of this so I'm a bit perplexed. If I try to run it on the server it yells at me that "import" is a reserved word. Then I tried to install babel and call ```require("babel/register");``` but that didn't really work out either.

```
export default function UniversalRenderer(alt, routes, html) {
  let render;
  // if it is not a browser
  if (typeof window === 'undefined') {
    // if there is a html string passed in
    // render the markup and inject it into the html string
    if (html) {
      render = (state, url) => {
        const markup = renderToMarkup(alt, routes, state, url);
        return html.replace('CONTENT', markup);
      };
    } else {
      render = (state, url) => {
        return renderToMarkup(alt, routes, state, url);
      };
    }
  } else {
    render = Iso.bootstrap((state, _, container) => {
      alt.bootstrap(state);
      Router.run(routes, Router.HistoryLocation, (Handler) => {
        let node = React.createElement(Handler);
        React.render(node, container);
      });
    });
  }

  return render;
}
```

Looking at the last else statement we are using history to grab the path anyways, so it should work O_O

**Comment by choonkending** [comment]
What happens is that webpack and babel compile the code into a function
which is used in routes.js in the server.

Nested routes shoudl work though. I'm currently working on a PR to use
react router 1.0 beta 3 so hopefully most of the issues will be resolved.
Still stuck with fixing it now :)

**Comment by choonkending** [comment]
@kkotwal94 Since the protected_routes change, has this still be an issue? I will close it if it has been resolved :)

**Comment by kkotwal94** [comment]
You can close!
