### ISSUE TITLE
Layout switching

### ISSUE THREAD

**Issue by praveen-ti** [choonkending/react-webpack-node#56]
How to create a new layout for admin here. What all are the changes needed in routes and webpack.config files.

**Comment by joshhornby** [comment]
@praveen-ti I have created a PR (#62) with outlines what you will need to do. The PR also has some new code with isn't relevant to what you need, so to outline:

1) Create a new class which will house the admin layout (https://github.com/choonkending/react-webpack-node/pull/62/files#diff-b9823c8ef410f4b456968a4046e79272R1)
2) In the `rotues.jsx` file you will want to wrap everything in a `<Route>` and then create a new block (https://github.com/choonkending/react-webpack-node/pull/62/files#diff-70012bb93dfce2be702a0251971c1db5R20)

Now in this case when the `login` route is hit, the layout will be taken from the `UnauthorisedApp` component and not the `App` component. 

Any questions let me know :+1:

**Comment by praveen-ti** [comment]
@joshhornby Thank you for you reply. I have fixed the issue. Created new layout for admin and switched layouts based on routing.
const routes = (
  <Route>
    <Route name="appadmin" path="/admin" handler={Admin} >
        <Route name="admin" handler={Adminlogin} />
        <Route name="/admin/login" handler={Adminlogin} />
        <Route name="/admin/logout" handler={Adminlogout} />
        <Route name="/admin/languages" handler={Languages} />
        <Route name="/admin/pages" handler={Pages} />
        <Route name="/admin/dashboard" handler={Dashboard} />
        <DefaultRoute handler={Adminlogin} />
        <NotFoundRoute name="404page" handler={NotFound} />
    </Route>
    <Route name="app" path="/" handler={App} >
      <Route name="login" handler={Login} />
      <Route name="logout" handler={Logout} />
      <Route name="index" handler={Index} />
      <Route name="signup" handler={Signup} />
      <Route name="signup/:hash" handler={Signup} />
      <DefaultRoute handler={Index} />
      <NotFoundRoute name="404" handler={NotFound} />
    </Route>
  </Route>
);

**Comment by praveen-ti** [comment]
Hi,
Thank you for your reply.  I have fixed the issue.




Regards,Praveen

**Comment by choonkending** [comment]
@joshhornby Too quick!
