### ISSUE TITLE
User state after login doesn't contain req.user data

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#57]
Since the new React Router PR (https://github.com/choonkending/react-webpack-node/pull/52) I am doing something like the following once a user has entered the correct details https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L80 

Once they get redirected the user store doesn't contain the server user state which can be seen here https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L62. The user state only contains what has been set at https://github.com/choonkending/react-webpack-node/blob/master/app/stores/UserStore.js#L67

Once I refresh the page the state contains the entire user object, this could be an issue with react router and the `transitionTo` but I am not sure.

**Comment by choonkending** [comment]
@joshhornby Hey I had a look into this. You can easily pass in the req.user object to be bootstrapped by alt.

Below is a horrid example:
```javascript
// Naming convention leaves a lot to be desired
var user = req.user ? { object: req.user, authenticated: true, isWaiting: false } : { object: null, authenticated: false, isWaiting: false };
```

Whereas your Dashboard.jsx could be something like:

```javascript
import React from 'react';
import UserStore from 'stores/UserStore';

export default class Dashboard extends React.Component {
  constructor(props) {
    super(props);
    this.state = UserStore.getState();
  }

  componentDidMount() {
    UserStore.listen(this._onChange);
  }

  componentWillUnmount() {
    UserStore.unlisten(this._onChange);
  }

  _onChange = () => {
    this.setState({
      user: UserStore.getState().user
    });
  }
  render() {
    console.log(this.state.user.get('object'));
    return (
      <div>Welcome to the Dashboard
        <div>{this.state.user.get('object').get('email')}</div>
      </div>

    );
  }
}

```

We'll be using AltContainer soon hopefully so none of this listen to stores for every high level component lol

**Comment by joshhornby** [comment]
@choonkending This still produces the same issue. After the intial login the user state only contains what has been set in the login action. Doing the example above doesn't work as `undefined` is returned when I do `props.user.get('object')` (I am already using AltContainer :+1: )

I will see if I can reproduce this bug this weekend and get an example repo online.

**Comment by choonkending** [comment]
@joshhornby Can you also have a look at https://github.com/choonkending/react-webpack-node/pull/61? This is how I got AltContainer working.

**Comment by joshhornby** [comment]
Sure. I'll base my example repo off this.

**Comment by choonkending** [comment]
@joshhornby Closing as it's been quite a big change since then. Let me know what you think of the current redux :)
