### ISSUE TITLE
requireAuth not getting hit on page load

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#58]
The `requireAuth` function (https://github.com/choonkending/react-webpack-node/pull/52/files#diff-70012bb93dfce2be702a0251971c1db5R13) which was introduced in the PR https://github.com/choonkending/react-webpack-node/pull/52 works great if I click on a route with has a `onEnter` attached to it. 

But if I visit a link via the url for example `localhost:3000/dashboard` I am redirected but the following line https://github.com/choonkending/react-webpack-node/pull/52/files#diff-70012bb93dfce2be702a0251971c1db5R15 is never hit. This means the app doesn't know where to redirect to once the user has logged it.

**Comment by choonkending** [comment]
Closing as issue will be fixed by this issue https://github.com/choonkending/react-webpack-node/issues/107
