### ISSUE TITLE
Can not use 'composes' syntax in CSS

### ISSUE THREAD

**Issue by hsin421** [choonkending/react-webpack-node#60]
The CSS modules set up is great. However, I can't seem able to use the 'composes' syntax in my css/scss files. (https://github.com/webpack/css-loader#composing-css-classes)

Does anyone have the same issue?

**Comment by hsin421** [comment]
Alright, I found that updating css-loader from 0.14.4 to 0.16.0 helps!

**Comment by choonkending** [comment]
@hsin421 Thanks for pointing this out. The css modules set up was all @psimyn :+1: 

I'm bumping out version up to 0.16.0 in case anyone wants to use composes too.
