### ISSUE TITLE
How to transitionTo after login/create/etc?

### ISSUE THREAD

**Issue by reactor81** [choonkending/react-webpack-node#65]
Hi, I want to transition to a new page I've made after login, or after adding a topic (in the demo app), etc. 

I've added the page to the routes.jsx <Route> section, and i can navigate to the page via URL no problem, or via <Link>..

But, what i need to do is navigate to a page of my choosing after creating a topic (e.g. in TopicActions.js or TopicStore.js (which is better and how can I do it?))

**Comment by joshhornby** [comment]
@reactor81 Take a look at this comment on this PR https://github.com/choonkending/react-webpack-node/pull/62#issuecomment-135037510 It should answer your question for you.

**Comment by reactor81** [comment]
This works great, thx!
