### ISSUE TITLE
react-router missing modules?

### ISSUE THREAD

**Issue by lucasmotta** [choonkending/react-webpack-node#68]
I've just downloaded a copy of this project and after installing the dependencies, I'm running:
```
npm run dev
```

But I get the following error, stating that it couldn't find a few modules inside [react-router](https://github.com/rackt/react-router):
https://gist.github.com/lucasmotta/37142dc1747389417d62 (error log)

And I couldn't find those files (used by react-webpack-node) on react-router:
- react-router/lib/Location
- react-router/lib/BrowserHistory

I am missing something?

**Comment by choonkending** [comment]
Thanks for letting us know. Nope you are not missing anything :)

The react router library had been upgraded (couple of days ago) and I
believe they ve moved those files out into a different repo.

I haven't had the chance to fix this yet, but I'm hoping to fix this week.

**Comment by lucasmotta** [comment]
Hey @choonkending, thanks for the quick reply. I think the main problem is described here: rackt/react-router#1820.
Since the API is constantly changing, maybe we should stick to the stable version (even thou with less features and different API) at least until version 1.0 is finally released.

**Comment by joshhornby** [comment]
@lucasmotta React router beta was added in this PR https://github.com/choonkending/react-webpack-node/pull/52 

Maybe its better changing this https://github.com/choonkending/react-webpack-node/blob/master/package.json#L63 to ```"react-router": "1.0.0-beta3"``` until v1

**Comment by lucasmotta** [comment]
@joshhornby yeah make sense to lock down to that specific version - that how I "fixed" on my side :)

**Comment by choonkending** [comment]
@joshhornby good call. I'll probably edit the package.json file to be fixed
until I find the time to ensure everything works on beta4
