### ISSUE TITLE
How does auto-login happen?

### ISSUE THREAD

**Issue by reactor81** [choonkending/react-webpack-node#72]
Can someone explain the startup-init flow that makes the user become automatically logged in when loading the page in a new window?

I login using the form, then close the window. When I come back, I am still logged in. 

I am trying to trace the client and server code to see how this is done, but I don't see it clearly.

**Comment by kraffslol** [comment]
If you look in the server routes.js you can see that state is sent through res.locals. Which is then handled by Iso in client.jsx. Which passes the state through to alt, and then sets the user data in the UserStore.

**Comment by reactor81** [comment]
Thanks!

**Comment by choonkending** [comment]
@kraffslol Thanks for explaining!! Closing issue!
