### ISSUE TITLE
Trouble running devhotloader

### ISSUE THREAD

**Issue by kkotwal94** [choonkending/react-webpack-node#76]
Running devHotLoader of a clean repo pull and opening up localhost:3000 gives me a error such as this: 

```Invariant Violation: renderToString(): You must pass a valid ReactElement.```

I thought this was a peerdependency problem so I added react and reactdom into the devDependencies in Package.json but that didnt resolve the problem. Is the hot loader not running on 3000? I know the assets are proxied from 3001/assets

**Comment by ojame** [comment]
@kkotwal94 did you end up finding a solution to this? I'm running into the same issue.

**Comment by kkotwal94** [comment]
Not at all actually, I asked on chat too. I tried searching it up and figuring out myself and this is what i found https://github.com/rackt/react-router/issues/2139

@choonkending any insight?

**Comment by ojame** [comment]
Ah. Thanks for replying so quick. I've tried updating the router from rc to 1.0.0, but no luck there either. I'll keep digging.

**Comment by kkotwal94** [comment]
Ill try as well right now.

**Comment by choonkending** [comment]
Might be the webpack config for dev being outdated. I will be looking to
using react-transform-hmr in the next few weeks.

**Comment by choonkending** [comment]
@kkotwal94 HMR is in! :) Closing this issue, but feel free to open a new issue if you find any bugs/improvements that can be made.
