### ISSUE TITLE
How to minify? 1.6 MB app.js file.. Other Tips?

### ISSUE THREAD

**Issue by reactor81** [choonkending/react-webpack-node#77]
I'm getting ready to deploy to production in a week or so, but have noticed the app.js file is very large > 1MB. 

I'd like to make it a lot smaller to make the download faster as it currently takes 5-7 seconds. 

Any thoughts on how to get minification going or any other tips for performance (particularly on initial download). I can see the network tab in google chrome dev tools takes a long time for the app.js file.

It's an m-class aws insance, so not the random accessibility t-class instance that would delay initial download.

**Comment by psimyn** [comment]
I don't think the prod task currently does minifying.

**Comment by choonkending** [comment]
@reactor81 You've probably already figured the minification part. But just for reference, you could uglify it like the webpack [file](https://github.com/choonkending/react-webpack-node/blob/master/webpack/webpack.config.prod.js#L126) on master branch right now. 

If you wish to optimise further, you can have a look at:
- what extra options you can pass into `webpack.optimize.UglifyJsPlugin`
- [CommonsChunkPlugin](https://github.com/webpack/docs/wiki/optimization#chunks)

I'm closing this issue as it's no longer happening on master. However, feel free to keep this thread running if you have any questions :)
