### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by kkotwal94** [choonkending/react-webpack-node#78]
I don't understand why a lot of my css is being overrided. For example if I have two different scss files for my sign up page and sign out page, it will load the css for whichever route i visited first. For example if signin has a red background, then signup will as well, even though the css I import for it has it set to blue(for signout). It also doesnt seem to be setting any of the 'id' or 'classnames'.

Here is my repository:

https://github.com/kkotwal94/ParsonsProject 

It has the same structure as the clean version of this, without topics though. A example is at components/login and /signup and the css is in the SCSS

**Comment by kkotwal94** [comment]
For the login issue i was having i was just not doing the wildcard get method on our server for checking req.user. Still havent figured out my css issue.

**Comment by kkotwal94** [comment]
Never mind I figured it out. Was having a derp moment here. I had to import styles from /scss/component_name, and then give the class of the element as
```className={styles['testclass']}

 //in scss

.testclass {
background-color:red;
}
```

Didn't have to do this in previous versions though, is this a scss update?

**Comment by choonkending** [comment]
@kkotwal94 Sorry for the late reply, not sure what you mean.

Do you mean that the way we access the style classes now are different? I.e. instead of `styles.about` we have to do `styles['about'] ` ?

**Comment by kkotwal94** [comment]
Yea, thats what I meant, I figured it out derp moment

**Comment by choonkending** [comment]
@kkotwal94 Cool. Closing issue.
