### ISSUE TITLE
can't set media queries in CSS modules

### ISSUE THREAD

**Issue by hsin421** [choonkending/react-webpack-node#79]
When I tried to write 

`@media (max-width: 400px) { ...}`

I got the error "Media query expression must begin with '('"

@psimyn what do you think is causing this? I searched and found others using media queries in CSS modules like normal. No one seemed to have this issue. Thanks

**Comment by psimyn** [comment]
odd, I'm able to use them. Where are you trying to add it? 

Are you using latest master? Can you upload a more complete snippet?
