### ISSUE TITLE
Migrate to Redux, maybe?

### ISSUE THREAD

**Issue by hsin421** [choonkending/react-webpack-node#80]
I am going to try migrating to Redux. 

1st step is to solve server side store hydrating with Iso + Redux. Any help?

Wish me luck.

**Comment by choonkending** [comment]
@hsin421 Haven't tried Iso + Redux yet. But really loving Redux and the way it s set up. Good luck!

I'm looking into other redux boilerplates that are good.

**Comment by hsin421** [comment]
@choonkending I have integrated Redux into the stack.
Would you like it on a separate branch?

**Comment by choonkending** [comment]
Yes please!!!

**Comment by choonkending** [comment]
I might have some thoughts on how Redux is added to the repo. Hopefully will get some time off to start crackin on this!

**Comment by choonkending** [comment]
@hsin421 Any update on this? I will have time to work on this in a week's time. :) Redux redux redux!!

**Comment by choonkending** [comment]
Changing to redux will be a pretty sweet move, but I'm just wondering if anyone disagrees with this. I'd prefer to merge this into the main branch once we finish.

**Comment by kkotwal94** [comment]
I'm down with that and react 14!

Altjs was pretty awesome was a great and easy implementation to learn flux from and how its useful.

**Comment by hsin421** [comment]
I apologize for getting back to this late. I have the basics done. I didn't push because in the rush I broke a lot of ESlint rules lol. And I agree with @choonkending that some others may prefer to stay with Alt. 
So I will clean up the code and push then.
