### ISSUE TITLE
Update to React 0.14!

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#82]

**Comment by bishopZ** [comment]
I made a boilerplate based from yours and did upgrade it to React 0.14. There were only a few changes which were covered pretty well in the upgrade guide. If my repo helps as a reference for this or anything else: https://github.com/bishopZ/kabuki-motion

**Comment by choonkending** [comment]
@bishopZ Thanks for that. I've made the changes in a https://github.com/choonkending/react-webpack-node/pull/84, just have not sorted out the extra warnings in console with AltContainer yet :D

**Comment by bishopZ** [comment]
Yeah, I ended up removing AltContainer in the short term. I was able to get
everything working by just importing the Store where necessary, fwiw.

On Wed, Oct 28, 2015 at 10:44 AM, Ken Ding <notifications@github.com> wrote:

> @bishopZ <https://github.com/bishopZ> Thanks for that. I've made the
> changes in a #84
> <https://github.com/choonkending/react-webpack-node/pull/84>, just have
> not sorted out the extra warnings in console with AltContainer yet :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choonkending/react-webpack-node/issues/82#issuecomment-151887751>
> .
>



-- 
________________________________________________________________
================================================================
=--------------------------------------------------------=-===-=-=-====--
+_+~_=_~--+__+=-^=-+_+_=^-+__+-=+_+~__=__~-_-____-=++=_--^-===-=-==-=-=--
=--------------------------------------------------------=-===-=-=-====--

http://bishopZ.com
_______________________________________________________________________

**Comment by choonkending** [comment]
Ready to merge
