### ISSUE TITLE
/app/server.jsx question

### ISSUE THREAD

**Issue by paulwehner** [choonkending/react-webpack-node#86]
How come most of the time when I print out the 'html' variable from 'base.html' within the server.js export function it is missing the closing head tag and class=app doesn't have quotes around app? I get this:

    <!DOCTYPE html><html><head><title>TITLE</title>META LINK<div class=app>CONTENT</div><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-XXXXX-X', 'auto');
    ga('send', 'pageview');</script><script type=text/javascript charset=utf-8 src=/assets/app.js></script>

**Comment by kkotwal94** [comment]
I think i had to add in the closing head tag too myself. Which should then workout fine, and as long as app works I think you are fine, I don't have quotes around my class app either, and my app works fine.

**Comment by choonkending** [comment]
@paulwehner I believe it was an issue with not updating react-helmet on my mission.

The latest version of master now uses redux, and no longer keeps base.html. Instead we just render a simple template in server.jsx [here](https://github.com/choonkending/react-webpack-node/blob/master/app/server.jsx#L32).

I'm closing this issue as it's no longer an issue in the latest master branch. Feel free to reopen it if you find any bugs.
