### ISSUE TITLE
Recommended approach for 'window' component dependency?

### ISSUE THREAD

**Issue by paulwehner** [choonkending/react-webpack-node#87]
I'm currently using 'slick-carousel' which references 'window'. I also do some references to window in some of my own react components to help with sizing of the component.

Do you have a recommended strategy for server side rendering, when I incorporate components into the project that reference 'window'?

**Comment by choonkending** [comment]
@paulwehner Thanks for asking. :)

A simple workaround for this is to check whether `typeof window !== 'undefined` when using window.

**Comment by choonkending** [comment]
Closing this issue but feel free to keep this thread running!
