### ISSUE TITLE
React Hot Loader => React Transform

### ISSUE THREAD

**Issue by hsin421** [choonkending/react-webpack-node#90]
Hot loader has been deprecated. 

What's the plan on transitioning to React Transform?

**Comment by choonkending** [comment]
Plan was to transition to transform together with redux/after. :)

**Comment by choonkending** [comment]
https://github.com/halt-hammerzeit/webpack-isomorphic-tools

**Comment by choonkending** [comment]
@hsin421 Give it a go. :)

**Comment by hsin421** [comment]
Wow major changes. 
Are you saying we should incorporate 'webpack-isomorphic-tools' ?
I will definitely give it a try, after I digest the recent changes!

**Comment by choonkending** [comment]
@hsin421 Yep I think that's a good next step to take. It might provide a better alternative to using webpack on the server than the approach we are currently taking.
