### ISSUE TITLE
Redux refactor + middleware + folder structure

### ISSUE THREAD

**Issue by choonkending** [choonkending/react-webpack-node#92]
Things to do asap:
- [x] Fix folder structure
- [x] Unneeded references to alt
- [x] Unneeded files
- [x] Fix server side rendering (refreshing on authenticated routes). It currently is very messy and can be made a lot simpler IMO. Details on possible implementation [here](https://github.com/rackt/redux-router/pull/45). Or perhaps use redux-simple-router.
![screenshot 2015-11-22 21 47 58](https://cloud.githubusercontent.com/assets/3787885/11323284/f19772ba-9162-11e5-929d-72aaa0b377ad.png)

- [x] Remove unneeded dependencies on master branch
- [x] Add middleware
- [x] Move container-level components to higher up. Currently very ugly. 
- [x] Remove pop up in production (heroku)
- [x] Use react transformer
- [ ] Consider using normalizr for the API responses for nested JSON (https://github.com/gaearon/normalizr)

**Comment by choonkending** [comment]
Problem with server-side redirects explained here http://stackoverflow.com/a/33338399

**Comment by choonkending** [comment]
Closing issue. We can reopen if we ever find the need for normalizr :D

**Comment by ArdentKid** [comment]
@choonkending I think I'm feeling the need for normalizr now. Anyone implementing it in their app? The docs are not the most clear, but I'll be hacking my way through it this weekend.
