### ISSUE TITLE
Error: Cannot find module 'reducers'

### ISSUE THREAD

**Issue by Pasta** [choonkending/react-webpack-node#95]
Hello,

I did:

git clone https://github.com/choonkending/react-webpack-node.git
npm install
npm run devHotLoader

Error is:

Error: Cannot find module 'reducers'

My node v = node v5.0.0
My npm v =  npm  v3.3.9

Did I forget something?

**Comment by choonkending** [comment]
@Pasta Thanks for raising this!

Just tested and verified that this issue does exist. Sorry about this, I'm currently looking into refactoring the codebase to be better, and part of that is removing hotloader and using react-transform-hmr instead. In the meantime, use  `npm run watch` to compile and `npm run dev` to start server.

If you like, I'd be happy to have a PR for using [react-transform-hmr](https://github.com/gaearon/react-transform-hmr)

**Comment by choonkending** [comment]
@Pasta Shouldn't have this issue anymore. Closing this issue, but feel free to comment.

**Comment by joernroeder** [comment]
same here with the current version and node `5.11.1`. 

```
ERROR in ./store/configureStore.js
Module not found: Error: Cannot resolve module 'reducers' in /app/store
 @ ./store/configureStore.js 19:16-35

> babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js" "index.js"

/public/assets/server.js:55825
	var _reducers = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"reducers\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
	                                                                                                                                                           ^

Error: Cannot find module "reducers"
```
